### DISCUSSION TITLE
Is there a need to Bind Nebula address when using multiple virtual IP Addresses?

### DISCUSSION THREAD

**Discussion by johnjces** [slackhq/nebula#1000] [Q&A] [answered]
BTW, I did Google and search github and etc. and never landed on anything regarding this. I'm certain there is somethign somewhere, but I didn't get the correct search i suppose. 

I am in the process of moving a bunch of specialty software,Nebula being one of them, to a Ubuntu box which has multiple virtual IP addresses. Actual physical address is 192.168.0.45. I had Nebula running successfully on a Raspberry Pi with a physical IP address of 192.168.0.15. Since I am lazy, I didn't want to redo any static routes that I had set on my router so I created a virtual IP of 192.168.0.15 on the Ubuntu box. It works well as I have unsafe routes on two LANs connected via Nebula miles apart. My T-LAN sees the WM-LAN (lighhouse) and vice- versa which is awesome. This has worked well for a coujple years (other than forgetting about the certificate expiry a few times), and works well on the Ubuntu box. EXCEPT:

I just "installed" the Windows version on my Win 11 Pro laptop, adding the unsafe routes of my LANs. The T-LAN, still on a raspberry pi with a physcial interface of 1.30, works great. I can see it's LAN just fine! But I cannot see the WM-LAN (Lighthouse) at all. I can ping and access the 1.15 address, the physical IP of 1.45 and one other virtual IP I have which I can't recall right now why I have it.

What did I miss in my config.yml file? There is no unsafe route in my cert for my laptop as who knows what LAN I might be on. ALso my IP of the laptop was no where near my WM-LAN (lighthouse) IP. Do I or should I set the virtual IP under:
listen:
  Hashtag To listen on both any ipv4 and ipv6 use "::"
  host: 192.168.0.15

...and should I also add my virtual IP to:
outbound:
    Hashtag Allow all outbound traffic from this node
    - port: any
      proto: any
      host: 192.168.0.15

This is the only thing I can think of that might be messing up my windows ability to see my unsafe route (LAN).

Thanks so much for any thoughts. Again, all is working well with a static route on my router (192.168.0.20) pointing to 0.15 for the current two node setup. One cloent and one lighthouse. Adding the windows Nebula in things are different. It can access on LAN but not the other,

Thanks so much for any help!

John

**Comment by johnmaguire** [comment]
Hi @johnjces - can you please post your config.yml's and log files from each host, removing any sensitive material such as the `pki.key` field? Thanks!

**Reply by johnjces** [reply]
Thanks John!

I am traveling and I can certainly do that hopefully sometime Sunday night 10/22 (or 10/23) if all goes to plan! At what level would you like logging?

John

**Reply by johnmaguire** [reply]
Sounds good. The default info level should be fine.

**Comment by johnjces** [comment]
@JohnMaguire

THANK-YOU!

Herein is a quick logfile and my config.yml file. As a reminder, I can access all devices on my 192.168.1.0/24 LAN and I can only access the lighthouse via local IP of 192.168.0.15 or 192168.98.1, the VPN IP on this Windows 11 Pro PC. Not seeing anything off in the log and I'm not seeing anything off in my config file but I am still learning! Also as a reminder, when I am local on either LAN I can see all devices. Just can't see the 0.0/24 LAN when away and on the WIndows Laptop. I reiterated this as sometimes when I try to explain things on forums I am not clear or confusing.

If I missed something, please let me know. Do you need any files from the lighthouse (192.168.0.0/24 node) or the Other lan, (192.168.1.0/24) node?

Uh oh... config.yml not displaying correctly even using the code tag. I had to remove all comments that had a hastag. I hope I didn't remove something necessary for your review.

logfile:
```
time="2023-10-23T16:58:53-07:00" level=info msg="Firewall rule added" firewallRule="map[caName: caSha: direction:outgoing endPort:0 groups:[] host:any ip: localIp: proto:0 startPort:0]"
time="2023-10-23T16:58:53-07:00" level=info msg="Firewall rule added" firewallRule="map[caName: caSha: direction:incoming endPort:0 groups:[] host:any ip: localIp: proto:0 startPort:0]"
time="2023-10-23T16:58:53-07:00" level=info msg="Firewall started" firewallHash=498215dec4e5687a2353f51c10838c113bd1af35ef72b8e8c9f536986ada5417
2023/10/23 16:58:53 Using existing driver 0.14
2023/10/23 16:58:53 Creating adapter
time="2023-10-23T16:58:54-07:00" level=warning msg="route MTU is not supported in windows" route="{1300 100 192.168.0.0/24 192.168.98.1 true}"
time="2023-10-23T16:58:54-07:00" level=warning msg="route MTU is not supported in windows" route="{1300 100 192.168.1.0/24 192.168.98.3 true}"
time="2023-10-23T16:58:54-07:00" level=info msg="Main HostMap created" network=192.168.98.4/24 preferredRanges="[]"
time="2023-10-23T16:58:54-07:00" level=info msg="punchy enabled"
time="2023-10-23T16:58:54-07:00" level=info msg="Loaded send_recv_error config" sendRecvError=always
time="2023-10-23T16:58:54-07:00" level=info msg="Nebula interface is active" boringcrypto=false build=1.7.2 interface=nebula1 network=192.168.98.4/24 udpAddr="[::]:4242"
time="2023-10-23T16:58:54-07:00" level=info msg="DNS results changed for host list" newSet="map[24.119.132.46:4242:{}]" origSet="&map[]"
time="2023-10-23T16:58:54-07:00" level=info msg="Handshake message sent" handshake="map[stage:1 style:ix_psk0]" initiatorIndex=1993547907 localIndex=1993547907 remoteIndex=0 udpAddrs="[24.119.132.46:4242]" vpnIp=192.168.98.1
time="2023-10-23T16:58:54-07:00" level=info msg="Handshake message received" certName=lighthouse durationNs=379954700 fingerprint=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx handshake="map[stage:2 style:ix_psk0]" initiatorIndex=1993547907 issuer=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx remoteIndex=1993547907 responderIndex=2709609364 sentCachedPackets=2 udpAddr="24.119.132.46:4242" vpnIp=192.168.98.1
time="2023-10-23T16:58:57-07:00" level=info msg="Handshake message sent" handshake="map[stage:1 style:ix_psk0]" initiatorIndex=2162105081 localIndex=2162105081 remoteIndex=0 udpAddrs="[76.29.210.210:4242 192.168.1.30:4242]" vpnIp=192.168.98.3
time="2023-10-23T16:58:58-07:00" level=info msg="Handshake message received" certName=client durationNs=1325777800 fingerprint=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx handshake="map[stage:2 style:ix_psk0]" initiatorIndex=2162105081 issuer=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx remoteIndex=2162105081 responderIndex=4118309518 sentCachedPackets=6 udpAddr="76.29.210.210:4242" vpnIp=192.168.98.3
time="2023-10-23T16:59:01-07:00" level=info msg="Handshake timed out" durationNs=7113469800 handshake="map[stage:1 style:ix_psk0]" initiatorIndex=891778952 localIndex=891778952 remoteIndex=0 udpAddrs="[]" vpnIp=192.168.98.255
time="2023-10-23T16:59:08-07:00" level=info msg="Handshake timed out" durationNs=6831740200 handshake="map[stage:1 style:ix_psk0]" initiatorIndex=3450004011 localIndex=3450004011 remoteIndex=0 udpAddrs="[]" vpnIp=192.168.98.255
time="2023-10-23T16:59:16-07:00" level=info msg="Handshake timed out" durationNs=6884999200 handshake="map[stage:1 style:ix_psk0]" initiatorIndex=1416313210 localIndex=1416313210 remoteIndex=0 udpAddrs="[]" vpnIp=192.168.98.255
time="2023-10-23T16:59:23-07:00" level=info msg="Handshake timed out" durationNs=7190091400 handshake="map[stage:1 style:ix_psk0]" initiatorIndex=922624213 localIndex=922624213 remoteIndex=0 udpAddrs="[]" vpnIp=192.168.98.255
time="2023-10-23T17:00:23-07:00" level=info msg="Handshake timed out" durationNs=6886443900 handshake="map[stage:1 style:ix_psk0]" initiatorIndex=2229027223 localIndex=2229027223 remoteIndex=0 udpAddrs="[]" vpnIp=192.168.98.255
time="2023-10-23T17:01:23-07:00" level=info msg="Handshake timed out" durationNs=7087110400 handshake="map[stage:1 style:ix_psk0]" initiatorIndex=2256744551 localIndex=2256744551 remoteIndex=0 udpAddrs="[]" vpnIp=192.168.98.255
````

config.yml

```
pki:
  ca: C:\Users\jjarrett\Applications\WinNebulaVPN\ca.crt
  cert: C:\Users\jjarrett\Applications\WinNebulaVPN\winclient.crt
  key: C:\Users\jjarrett\Applications\WinNebulaVPN\winclient.key

static_host_map:
 "192.168.98.1": ["mydomain.com:4242"]
 #"192.168.98.1": []

lighthouse:
  interval: 60

  am_lighthouse: false

  hosts:
    - "192.168.98.1"

listen:
  host: 0.0.0.0
  port: 4242

punchy: true

punch_back: true

punchy:
  respond: false
  delay: 1s
relay:
  am_relay: false
  use_relays: true

tun:
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300
  
  routes:

  unsafe_routes:
    - route: 192.168.0.0/24
      via: 192.168.98.1
      mtu: 1300
      metric: 100
    - route: 192.168.1.0/24
      via: 192.168.98.3
      mtu: 1300
      metric: 100

logging:
  level: info
  format: text

firewall:
  conntrack:
    tcp_timeout: 120h
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000

  outbound:
    - port: any
      proto: any
      host: any

  inbound:
    - port: any
      proto: any
      host: any
```

**Comment by johnjces** [comment]
Here is the lighthouse config.yml with hashtags/comments removed. This is the 192.168.0.0/24 LAN that I cannot see except for the box nebula is running.

```
pki:
  ca:   /opt/NebulaVPN/ca.crt
  cert: /opt/NebulaVPN/lighthouse.crt
  key:  /opt/NebulaVPN/lighthouse.key

static_host_map:
  "192.168.98.1": ["mydomain.com:4242"]

lighthouse:
  interval: 60

  am_lighthouse: true

  hosts:

listen:
  host: 192.168.0.15
  port: 4242

punchy:
  punch: true
  respond: true
  delay: 1s

relay:
  am_relay: false
  use_relays: true

tun:
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300
  routes:
  unsafe_routes:
    - route: 192.168.1.0/24
      via: 192.168.98.3

logging:
  level: info
  format: text

firewall:
  conntrack:
    tcp_timeout: 120h
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000

  outbound:
    - port: any
      proto: any
      host: any

  inbound:
    - port: any
      proto: any
      host: any
```
