### DISCUSSION TITLE
Firewall connection tracker

### DISCUSSION THREAD

**Discussion by Ripper346** [slackhq/nebula#1040] [General]
Hi, I am trying to understand the meanings behind the `firewall.conntrack` options. In the documentation it is reported
```
Settings for the Connection Tracker.

conntrack:
  tcp_timeout: 12m
  udp_timeout: 3m
  default_timeout: 10m
```
What are the timeouts referred to? Like `tcp_timeout` refers to drop all the TCP connections after 12 minutes, or is it in some cases? In case the default is less than the specific (like for TCP) does it overwrite the rule? I am not very into firewall rules, so sorry if these may be dumb questions. Thank you
