### DISCUSSION TITLE
Error while validating outbound packet: packet is not ipv4, type: 6

### DISCUSSION THREAD

**Discussion by Ripper346** [slackhq/nebula#1349] [Q&A]
Hi, I have set up a lighthouse on a docker container in a server exposing only port 4242 udp. With regular hosts, it works fine. Then, I tried to set up a host that I am able to connect to only through a VPN. I wasn't able to connect via nebula, and I noticed the following error after trying the handshake that is visible only with debugging level.
```
level=debug msg="Error while validating outbound packet: packet is not ipv4, type: 6" packet="[96 0 0 0 0 8 58 255 254 128 0 0 0 0 0 0 18 ...]"
```
I thought, ok, there is some sort of block maybe and passed to the next host to configure. This time, I set up a docker container with nebula to make a port available in another nebula host through that server from outside. In the beginning, it didn't work, but then I was able to make it work due to some configuration errors. However, sometimes, the logs will show the same error from above. 

What does this error mean? All my hosts work in ipv4 (except the one behind the VPN that I don't know how it is configured, but since it didn't work, I turned it off). Moreover, since they are on the same server, the latter nebula in docker I mentioned is working through an internal ipv4 docker network. I hope that if I understand this error, I will maybe understand why the host behind the VPN isn't making the handshake with the lighthouse. Thank you.

In the lighthouse, at the moment, I have this configuration:
```yaml
pki:
  ca: ./ca.crt
  cert: ./lighthouse1.crt
  key: ./lighthouse1.key

lighthouse:
  am_lighthouse: true
  interval: 60

listen:
  host: 0.0.0.0
  port: 4242

punchy:
  punch: true

relay:
  am_relay: true
  use_relays: true

tun:
  disabled: false
  dev: nebula_personal
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300
  routes:
  unsafe_routes:

logging:
  level: info
  format: text

firewall:
  outbound_action: drop
  inbound_action: drop

  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m

  outbound:
    - port: any
      proto: any
      host: any

  inbound:
    - port: any
      proto: any
      host: any
```

**Comment by johnmaguire** [comment]
Sorry for the very late response.

This log message is most likely a red herring. This indicates that an IPv6 packet has ended up on Nebula interface. Nebula (prior to the current nightly release) supports only IPv4 overlay addresses, so it can only handle IPv4 packets. Usually this is the result of some multicast stuff occuring on the host and can be safely ignored.

Perhaps you can provide logs from the affected hosts? I'd be happy to take a look.

In the meantime, one tidbit I can share is that I run Nebula on a Docker host with many containers and internal networks. I don't run it in a container, but on the host itself. I found myself losing connectivity to the host at times. This was because the Lighthouse will only record the last 20 IP addresses reported by a host. My host was reporting far more than 20 IP addresses in private Docker (unroutable) addresses alone.

To address this, I run with the following config:

```
    local_allow_list:
      interfaces:
        br-.*: false
        docker.*: false
        veth.*: false
```

This ensures that my Docker host doesn't report the IP addresses of its Docker containers as if they would be routable from other machines.
