### DISCUSSION TITLE
Unreliable Network-dependent Connections

### DISCUSSION THREAD

**Discussion by ghost** [slackhq/nebula#1396] [Q&A] [answered]
First, hello all! 

### Description

I switched over from Tailscale to Nebula a few weeks ago and have mostly enjoyed it so far. Unfortunately, I'm having some reliability issues. When I'm on certain networks (airplanes, some coffee shops, etc) Nebula has refused to work when I haven't had time to debug. 

Now that I have time to debug a bit, it looks like it's latching onto `fd42:8fd1:ab8f:bcdb::1:4242` and not letting go. I can try to let a ping run for >5 minutes and I won't get a single response. When I switch networks (ex. from a problematic coffee shop wifi to my phone's hotspot which always seems to work) then I see the **exact** same list of addresses in the `udpAddrs` list but it it fails to fallback from that ipv6 address.  Here's hoping there is a simple problem with my config!

Secondarily, I don't think I've ever seen relays work even though I have them enabled. Maybe that's causing a problem?

### Details

```zsh
$ nebula -version
Version: 1.9.5-Fedora
```
Laptop config:
```yaml
pki:
  ca: /opt/nebula/ca.crt
  cert: /opt/nebula/host.crt
  key: /opt/nebula/host.key

static_host_map:
  "42.69.0.1": ["[public-ip-here]:4242"]

static_map:
  cadence: 30s
  network: ip4
  lookup_timeout: 250ms

lighthouse:
  am_lighthouse: false
  serve_dns: false
  hosts:
    - "42.69.0.1"

listen:
  host: "::"
  port: 0

punchy:
  punch: true

relay:
  relays:
    - 42.69.0.1
  use_relays: true

tun:
  disabled: false
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300

  routes:
    #- mtu: 8800
    #  route: 10.0.0.0/16

logging:
  format: text

firewall:
  outbound_action: drop
  inbound_action: drop

  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m

  outbound:
    - port: any
      proto: any
      host: any

  inbound:
    - port: any
      proto: icmp
      host: any
```

Happy to add my server config if needed.

**Comment by johnmaguire** [comment]
Hi @luc-spec -

It's hard to say what's going on without logs. Can you provide logs from the affected hosts? Also, you mentioned relays aren't working - I see that you've configured `relay.use_relays: true` and added `42.69.0.1` to the list of `relay.relays`. Can you share the config for this relay/lighthouse (which must have `relay.am_relay: true` set)?

**Reply by ghost** [reply]
Thanks for the reply! 

Here is the config for my relay/lighthouse:

```
firewall:
  inbound:
  - host: any
    port: any
    proto: icmp
  - host: any
    port: 53
    proto: udp
  inbound_action: drop
  outbound:
  - host: any
    port: any
    proto: any
  outbound_action: drop
lighthouse:
  am_lighthouse: true
  dns:
    host: '[::]'
    port: 53
  hosts: []
  serve_dns: true
listen:
  host: '[::]'
  port: 4242
pki:
  ca: /opt/nebula/ca.crt
  cert: /opt/nebula/host.crt
  key: /opt/nebula/host.key
punchy:
  punch: true
relay:
  am_relay: true
  relays: []
  use_relays: true
static_host_map: {}
tun:
  dev: nebula1
  disabled: false
```

Lighthouse/relay logs attached, with public IPs removed by the script below. Adding the script too in case anyone else is interested.

[nebula-lighthouse-relay-logs-20250509.txt](https://github.com/user-attachments/files/20127283/nebula-lighthouse-relay-logs-20250509.txt)

```python
#!/usr/bin/env python3

import re

def find_and_replace_ip4(filename, search_pattern=r'\b(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})\b'):
    pub_ips = {}
    counter = 1
    keep_these = [ 
      '42.69.0.1',
      '42.69.77.11',
      '42.69.77.22',
      '42.69.77.33'
      ]
    with open(filename, 'r') as f:
        lines = f.readlines()
   
    with open(filename, 'w') as f:
        for line in lines:
            if re.search(search_pattern, line):
                ip = re.search(search_pattern, line).group()
                if ip not in keep_these:
                    if ip not in pub_ips.keys():
                        pub_ips[ip] = f'public-ip-{counter}'
                        counter += 1
                    l = line.replace(ip, f'[{pub_ips[ip]}]')
                    print(f'found public ip: {ip}; replacing with {l}')
                    f.write(l)
                else:
                    f.write(line)
            else:
                f.write(line)

if __name__ == '__main__':
    for i in range(1,5):
        # out of laziness just run it a few times to catch
        # multiple ips per line
        print(f'=== Run {i} ===')
        find_and_replace_ip4('/tmp/nebula-lighthouse-relay-logs-20250509.txt')
```
