### DISCUSSION TITLE
Controlling access to subnet routing

### DISCUSSION THREAD

**Discussion by xppppp** [slackhq/nebula#944] [Q&A]
I am trying to control which nodes can access subnet routing (via `tun.unsafe_routes`).  So, in `firewall.inbound` on the edge node that provides access to the subnet I have:

```
    - port: any

      proto: any

      groups:

        - canaccess

        - allaccess
```

With that in the configuration, we can ping the edge node, the routes appear on the remote nodes, but everything on the unsafe subnet is inaccessible.  If we change the configuration on the edge node to:

```
    - port: any

      proto: any

      host: any
```

then it all works.  Have I missed something?
