### ISSUE TITLE
🐛 BUG: No normal communication between the two machines

### ISSUE THREAD

**Issue by QZAiXH** [slackhq/nebula#1007]
### What version of `nebula` are you using?

50d6a1e8cae1fa60668f62405e2020e990706cf7

### What operating system are you using?

Linux, Windows

### Describe the Bug

I have two computer devices, one serving as a server running on a Linux system, and the other as a client (J1exwzkmO3) running on a Windows system. Although both the server and client can successfully ping the lighthouse IP, the two nodes are unable to ping each other.

## server config

```
pki:
    ca: |
        -----BEGIN NEBULA CERTIFICATE-----
        Cj8KDUZsYXNoTkFTLCBJbmMo77msqgYw767RqgY6IGmVp2PSlZueWAdFX4bF/cmR
        bBoaomJwGjQxVygplsZqQAESQEwmSzPNMn7N3/6zNO5mRBT4KpbGjc9ckJ6GJyBN
        ZU+LFtrRW+tMhLDv5ZBBZQzcgdnJGkh/7/ikiDp580g3yA0=
        -----END NEBULA CERTIFICATE-----
    cert: |
        -----BEGIN NEBULA CERTIFICATE-----
        CmgKCjIyZURpY2hNazUSCvmExOAKgID8/w8o7cOxqgYw7ea2qgY6IEBGabnXjAZQ
        T+IKfcmNYKo4DBezDOuuE/htL0616d82SiAjnIJwIkcO+SQ3PYa1ueK/OdqseNaY
        pQlRtPjBxKh8ohJALkFmsku5+5V2/6kvO7sn1OTp8xxIWGNS3QeMt+vrTq6wMJyh
        onb2oFRLW1LGjMwSAwepNraQSphoA0S3uBQmCA==
        -----END NEBULA CERTIFICATE-----
    key: |
        <EDIT - removed>
    blocklist: []
    disconnect_invalid: true
static_host_map:
    172.17.0.1:
        - xx.xx.xx.xx:4242
lighthouse:
    am_lighthouse: false
    interval: 60
    hosts:
        - 172.17.0.1
listen:
    host: 0.0.0.0
    port: 0
routines: 4
punchy:
    punch: true
    respond: true
    delay: 1s
    respond_delay: 5s
cipher: aes
relay:
    relays:
        - 172.17.0.1
    am_relay: false
    use_relays: true
tun:
    disabled: false
    dev: fsnb0
    drop_local_broadcast: false
    drop_multicast: false
    tx_queue: 500
    mtu: 1300
    routes: []
    unsafe_routes: []
logging:
    level: info
    format: text
firewall:
    outbound_action: reject
    inbound_action: reject
    conntrack:
        tcp_timeout: 12m
        udp_timeout: 3m
        default_timeout: 10m
    outbound:
        - port: any
          proto: any
          host: any
    inbound:
        - port: any
          proto: any
          host: QJQ9Y27L3Q
        - port: any
          proto: any
          host: KHb9UiFXhO
        - port: any
          proto: any
          host: PUHEnGWvse
        - port: any
          proto: any
          host: NHCNbOU5kS
        - port: any
          proto: any
          host: gNANVz7gEh
        - port: any
          proto: any
          host: J1exwzkmO3
        - port: any
          proto: any
          host: VY7AmqGc9C
        - port: any
          proto: any
          host: 1qLWmUAhwS
        - port: any
          proto: any
          host: AioSyObMTI
        - port: any
          proto: any
          host: t5ph5mcgrU
        - port: any
          proto: any
          host: VAV6PaP9xy
        - port: any
          proto: icmp
          host: any
```

## client config

```
pki:
    ca: |
        -----BEGIN NEBULA CERTIFICATE-----
        Cj8KDUZsYXNoTkFTLCBJbmMo77msqgYw767RqgY6IGmVp2PSlZueWAdFX4bF/cmR
        bBoaomJwGjQxVygplsZqQAESQEwmSzPNMn7N3/6zNO5mRBT4KpbGjc9ckJ6GJyBN
        ZU+LFtrRW+tMhLDv5ZBBZQzcgdnJGkh/7/ikiDp580g3yA0=
        -----END NEBULA CERTIFICATE-----
    cert: |
        -----BEGIN NEBULA CERTIFICATE-----
        CmgKCkoxZXh3emttTzMSCpSGxOAKgID8/w8oqeuxqgYwqY63qgY6IC6HHxGoUPhe
        AoE5LLZuF3NebXY8cizTIUf2FYvncLZcSiAjnIJwIkcO+SQ3PYa1ueK/OdqseNaY
        pQlRtPjBxKh8ohJAsxf3ePMXewZE2VUjiD2DBCT5+b+B+ki/nkS6t0nsrwsGtdmz
        7GmHNYU4wwjl+avA56bGou0C7/nSZzQuxF3NDg==
        -----END NEBULA CERTIFICATE-----
    key: |
       < EDIT - removed >
    blocklist: []
    disconnect_invalid: true
static_host_map:
    172.17.0.1:
        - xx.xx.xx.xx:4242
lighthouse:
    am_lighthouse: false
    interval: 60
    hosts:
        - 172.17.0.1
listen:
    host: 0.0.0.0
    port: 0
routines: 1
punchy:
    punch: true
    respond: true
    delay: 1s
    respond_delay: 5s
cipher: aes
relay:
    relays:
        - 172.17.0.1
    am_relay: false
    use_relays: true
tun:
    disabled: false
    dev: fsnb0
    drop_local_broadcast: false
    drop_multicast: false
    tx_queue: 500
    mtu: 1300
    routes: []
    unsafe_routes: []
logging:
    level: info
    format: text
firewall:
    outbound_action: reject
    inbound_action: reject
    conntrack:
        tcp_timeout: 12m
        udp_timeout: 3m
        default_timeout: 10m
    outbound:
        - port: any
          proto: any
          host: any
    inbound:
        - port: any
          proto: icmp
          host: any
```

## lighthouse config

```
pki:
    ca: |
        -----BEGIN NEBULA CERTIFICATE-----
        Cj8KDUZsYXNoTkFTLCBJbmMo77msqgYw767RqgY6IGmVp2PSlZueWAdFX4bF/cmR
        bBoaomJwGjQxVygplsZqQAESQEwmSzPNMn7N3/6zNO5mRBT4KpbGjc9ckJ6GJyBN
        ZU+LFtrRW+tMhLDv5ZBBZQzcgdnJGkh/7/ikiDp580g3yA0=
        -----END NEBULA CERTIFICATE-----
    cert: |
        -----BEGIN NEBULA CERTIFICATE-----
        CmgKCmdPUURBa1Q0WHcSCoGAxOAKgID8/w8oxMGxqgYwxOS2qgY6IGLMrwdaShU2
        j6gYiuSRPLqZ4Liqsx7xABURmutjIHtdSiAjnIJwIkcO+SQ3PYa1ueK/OdqseNaY
        pQlRtPjBxKh8ohJAv/++FkG+t/eNXQQhvh7KK2qK7uGkGW9d0hqi15/eotB8+A7F
        2IYsxsEE9BcUyUsngikKKqP37EWBNoXH7MRwCg==
        -----END NEBULA CERTIFICATE-----
    key: |
        < EDIT - removed>
    blocklist: []
    disconnect_invalid: true
static_host_map:
    172.17.0.1:
        - xx.xx.xx.xx:4242
lighthouse:
    am_lighthouse: true
    interval: 60
    hosts: []
listen:
    host: 0.0.0.0
    port: 4242
routines: 4
punchy:
    punch: true
    respond: true
    delay: 1s
    respond_delay: 5s
cipher: aes
relay:
    relays: []
    am_relay: true
    use_relays: false
tun:
    disabled: false
    dev: fsnb0
    drop_local_broadcast: false
    drop_multicast: false
    tx_queue: 500
    mtu: 1300
    routes: []
    unsafe_routes: []
logging:
    level: info
    format: text
firewall:
    outbound_action: reject
    inbound_action: reject
    conntrack:
        tcp_timeout: 12m
        udp_timeout: 3m
        default_timeout: 10m
    outbound:
        - port: any
          proto: any
          host: any
    inbound:
        - port: any
          proto: icmp
          host: any
```
