### ISSUE TITLE
🐛 BUG:unsafe_unsafe routes: same subnet but different via IP address but could not reach the site

### ISSUE THREAD

**Issue by Magesh07subramanian** [slackhq/nebula#1008]
### What version of `nebula` are you using?

1.6.1

### What operating system are you using?

windows and mac

### Describe the Bug
We have configured a nebula unsafe route to reach a resource where we cannot configure a nebula. It works fine if we have different subnets, but it doesn't work if we have same subnet on an unsafe route
 
Example:
 
  #1

```
route: 10.152.0.0/20
  via: 192.168.18.17
  mtu: 1300
  metric: 100
```

  #2

```
route: 10.152.0.0/20
  via: 192.168.5.1 
  mtu: 1300
  metric: 100
```

1 and 2 routes have the same subnet but different IP addresses. If we turn on the nebula and try to reach the resource on the first unsafe route, the nebula is only taking the second unsafe route, and we cannot reach that resource.
 
Both subnets are in different projects in the cloud; there is no communication between them, and we have enabled nebula and forwarding in two different VMs in their respective projects.
 
Note: If we use any one of the above safe routes, we can reach the resource.
 
Whether the nebula will work like this any workaround?

### Config files from affected hosts

```
unsafe_routes:
route: 10.152.0.0/20----------------------------->1
      via: 192.168.18.17
      mtu: 1300
      metric: 100
      
route: 10.152.0.0/20------------------------>2
      via: 192.168.5.1 
      mtu: 1300
      metric: 100
```
