### ISSUE TITLE
lighthouse.dns.host does not accept ::, but listen.host does

### ISSUE THREAD

**Issue by Pandapip1** [slackhq/nebula#1100]
### What version of `nebula` are you using? (`nebula -version`)

1.6.1

### What operating system are you using?

Linux (Debian bookworm)

### Describe the Bug

When trying to use IPv6 for the DNS server, I get the following error: `Failed to start server: listen udp: address :::53: too many colons in address`

### Logs from affected hosts

```json
root@lighthouse:/etc/nebula# nebula -config ./config.yml 
{"firewallRule":{"caName":"","caSha":"","direction":"outgoing","endPort":0,"groups":null,"host":"any","ip":"","proto":0,"startPort":0},"level":"info","msg":"Firewall rule added","time":"2024-03-29T15:56:18Z"}
{"firewallRule":{"caName":"","caSha":"","direction":"incoming","endPort":0,"groups":null,"host":"any","ip":"","proto":0,"startPort":0},"level":"info","msg":"Firewall rule added","time":"2024-03-29T15:56:18Z"}
{"firewallHash":"21716b47a7a140e448077fe66c31b4b42f232e996818d7dd1c6c4991e066dbdb","level":"info","msg":"Firewall started","time":"2024-03-29T15:56:18Z"}
{"level":"info","msg":"Main HostMap created","network":{"IP":"10.0.0.1","Mask":"////AA=="},"preferredRanges":null,"time":"2024-03-29T15:56:18Z"}
{"level":"info","msg":"UDP hole punching enabled","time":"2024-03-29T15:56:18Z"}
{"level":"info","msg":"Loaded send_recv_error config","sendRecvError":"always","time":"2024-03-29T15:56:18Z"}
{"build":"1.6.1","interface":"nebula0","level":"info","msg":"Nebula interface is active","network":"10.0.0.1/24","time":"2024-03-29T15:56:18Z","udpAddr":{"ip":"::","port":4242}}
{"dnsListener":":::53","level":"info","msg":"Starting DNS responder","time":"2024-03-29T15:56:18Z"}
{"level":"error","msg":"Failed to start server: listen udp: address :::53: too many colons in address\n ","time":"2024-03-29T15:56:18Z"}
^C
{"level":"info","msg":"Caught signal, shutting down","signal":"interrupt","time":"2024-03-29T15:56:19Z"}
{"level":"info","msg":"Goodbye","time":"2024-03-29T15:56:19Z"}
```

### Config files from affected hosts

```yml
pki:
  ca: /etc/nebula/ca.crt
  cert: /etc/nebula/lighthouse.crt
  key: /etc/nebula/lighthouse.key

static_host_map:

lighthouse:
  am_lighthouse: true
  serve_dns: true
  dns:
    host: "::"
    port: 53

listen:
  host: "::"
  port: 4242

punchy:
  punch: true

sshd:
  enabled: false

relay:
  am_relay: false
  use_relays: false

tun:
  disabled: false
  dev: nebula0
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300
  use_system_route_table: true

logging:
  level: info
  format: json

firewall:
  outbound_action: drop
  inbound_action: drop

  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m

  outbound:
    # Allow all outbound traffic from this node
    - port: any
      proto: any
      host: any

  inbound:
    # Allow all inbound traffic to this node
    - port: any
      proto: any
      host: any
```
