### ISSUE TITLE
🐛 `relay.am_relay` not working

### ISSUE THREAD

**Issue by AliasQli** [slackhq/nebula#1192]
### What version of `nebula` are you using? (`nebula -version`)

1.9.3

### What operating system are you using?

Linux

### Describe the Bug

I have a lighthouse with a public IP and `relay.am_relay = true`, and 2 clients which is under NAT. Each client can connect to the lighthouse, but they can't find each other. Moreover, ssh shows

```
root@nebula > print-relays
{"Relays":null}
```

both on the lighthouse and the clients. The log shows nothing important. So is `relay.am_relay` just not working?

### Logs from affected hosts

Lighthouse:
```
time="2024-08-07T05:49:39+08:00" level=info msg="Handshake message received" certName=Client fingerprint=999bbad9e018b2b575e42c4cb1cce0fc45d462342752710a771b2c3073eb14da handshake="map[stage:1 style:ix_psk0]" initiatorIndex=2793272169 issuer=5e7b2e68f061ae01819c133275b1aed8ec6fdfcddb9cdd28a35dd7bdad16b7ad remoteIndex=0 responderIndex=0 udpAddr="<Client IP>:1476" vpnIp=192.168.14.112
time="2024-08-07T05:49:39+08:00" level=info msg="Taking new handshake" certName=Client localIndex=1213800407 remoteIndex=2508575555 vpnIp=192.168.14.112
time="2024-08-07T05:49:39+08:00" level=info msg="Handshake message sent" certName=Client fingerprint=999bbad9e018b2b575e42c4cb1cce0fc45d462342752710a771b2c3073eb14da handshake="map[stage:2 style:ix_psk0]" initiatorIndex=2793272169 issuer=5e7b2e68f061ae01819c133275b1aed8ec6fdfcddb9cdd28a35dd7bdad16b7ad remoteIndex=0 responderIndex=4168221311 udpAddr="<Client IP>:1476" vpnIp=192.168.14.112
time="2024-08-07T05:49:40+08:00" level=info msg="Handshake message received" certName=Client fingerprint=999bbad9e018b2b575e42c4cb1cce0fc45d462342752710a771b2c3073eb14da handshake="map[stage:1 style:ix_psk0]" initiatorIndex=2793272169 issuer=5e7b2e68f061ae01819c133275b1aed8ec6fdfcddb9cdd28a35dd7bdad16b7ad remoteIndex=0 responderIndex=0 udpAddr="<Client IP>:1476" vpnIp=192.168.14.112
time="2024-08-07T05:49:40+08:00" level=info msg="Handshake message sent" cached=true handshake="map[stage:2 style:ix_psk0]" udpAddr="<Client IP>:1476" vpnIp=192.168.14.112
time="2024-08-07T05:49:51+08:00" level=info msg="Tunnel status" certName=Client localIndex=1213800407 remoteIndex=2508575555 tunnelCheck="map[method:active state:dead]" vpnIp=192.168.14.112
```

Client:
```
time="2024-08-07T05:49:39+08:00" level=info msg="Handshake message sent" handshake="map[stage:1 style:ix_psk0]" initiatorIndex=2793272169 localIndex=2793272169 remoteIndex=0 udpAddrs="[<Lighthouse IP>:4242]" vpnIp=192.168.14.1
time="2024-08-07T05:49:40+08:00" level=info msg="Handshake message received" certName=Lighthouse durationNs=428348314 fingerprint=3d0376591ab1340fbf52cf0b947fcd2a3b5377f3ccd4b4beb1ae30d0165b7e5e handshake="map[stage:2 style:ix_psk0]" initiatorIndex=2793272169 issuer=5e7b2e68f061ae01819c133275b1aed8ec6fdfcddb9cdd28a35dd7bdad16b7ad remoteIndex=2793272169 responderIndex=4168221311 sentCachedPackets=1 udpAddr="<Lighthouse IP>:4242" vpnIp=192.168.14.1
time="2024-08-07T05:50:11+08:00" level=info msg="Tunnel status" certName=Lighthouse localIndex=2793272169 remoteIndex=4168221311 tunnelCheck="map[method:active state:dead]" vpnIp=192.168.14.1
```

### Config files from affected hosts

Lighthouse:
```
pki:
  # ...

static_host_map:

lighthouse:
  am_lighthouse: true

listen:
  host: 0.0.0.0
  port: 4242

relay:
  am_relay: true

firewall:
  outbound:
    - port: any
      proto: any
      host: any

  inbound:
    - port: any
      proto: any
      host: any

sshd:
  enabled: true
  listen: 0.0.0.0:4241
  # ...
```

Client:
```
firewall:
  inbound:
  - host: any
    port: any
    proto: any
  outbound:
  - host: any
    port: any
    proto: any
lighthouse:
  am_lighthouse: false
  hosts:
  - 192.168.14.1
listen:
  host: 0.0.0.0
  port: 0
pki:
  # ...
relay:
  am_relay: false
  relays:
  - 192.168.14.1
  use_relays: true
sshd:
  enabled: true
  listen: 127.0.0.1:4241
  #...
static_host_map:
  192.168.14.1:
  - <Lighthouse IP>:4242
tun:
  dev: nebula.some-name
  disabled: false
```
