### ISSUE TITLE
🐛 BUG: "Listener is IPv4, but writing to IPv6 remote" error is usually unhelpful

### ISSUE THREAD

**Issue by johnmaguire** [slackhq/nebula#1227]
### What version of `nebula` are you using? (`nebula -version`)

1.9.4

### What operating system are you using?

Linux

### Describe the Bug

When the Lighthouse tells a host about an IPv6 address and it attempts to handshake, this error occurs if the host has IPv4 disabled or `listen.host` set to 0.0.0.0. This confuses a lot of users into thinking it's the cause of (whatever issues they happen to be having.)

Maybe we can make this message warning-level, debug-level, less frequent, more informative, or occur in fewer configurations?

### Logs from affected hosts

n/a

### Config files from affected hosts

n/a

**Comment by erikschul** [comment]
You mention "if the host has **IPv6** disabled" ?

**Comment by migs35323** [comment]
I have a problem that might be related,

I have setup in all my nodes:
```
static_map:
  network: ip4
listen:
  host: 0.0.0.0
  port: 4242
static_host_map:
  "10.10.10.10":
    - "1.1.1.1:4242"
    - "lighthouse.example.com:4242"
```


however it happears they seem to be connecting using ipv6...
`error="Listener is IPv4, but writing to IPv6 remote" handshake="map[stage:1 style:ix_psk0]" initiatorIndex=932224779 localIndex=932224779 remoteIndex=0 udpAddr="[2a2a:2a2a:2a2a:2a2a::2]:`

theese specific nodes have both ipv4 and ipv6 in the eth interface. 
i wanted to only use ipv4 but keep the ipv6 at the system level enabled....

i believe either the message is wrong or nebula is ignoring the static map directive...
