### ISSUE TITLE
🐛 BUG: noise: unexpected call to ReadMessage should be WriteMessage

### ISSUE THREAD

**Issue by migs35323** [slackhq/nebula#1317]
### What version of `nebula` are you using? (`nebula -version`)

1.9.5

### What operating system are you using?

ubuntu 22 (cloud img)

### Describe the Bug

I have a proxmox setup where i have several Virtual machines connected trough nebula (makes stuff portable to migrate and vpn access)
in each node there is a network interface to the internet.
I added a virtual host only network so Virtual machines can "go very fast" with each other without going trough the real network interface, and take advantage of a big mtu to take advantage..
but now i am getting theese errors

### Logs from affected hosts

node-2
```
node-2 nebula[367]: time="2025-01-27T18:05:45Z" level=error msg="Failed to call noise.ReadMessage" error="noise: unexpected call to ReadMessage should be WriteMessage" handshake="map[stage:2 style:ix_psk0]" header="ver=1 type=handshake subtype=ix_psk0 reserved=0x0 remoteindex=689285047 messagecounter=2" udpAddr="192.168.120.14:4203" vpnIp=192.168.69.53


```
in the other node i got the same error but for a third node

### Config files from affected hosts

```

firewall:
  conntrack:
    default_timeout: 10m
    tcp_timeout: 12m
    udp_timeout: 3m
  inbound:
  - host: any
    port: any
    proto: any
  inbound_action: reject
  outbound:
  - host: any
    port: any
    proto: any
  outbound_action: reject
lighthouse:
  advertise_addrs:
  - <port-foward-ip:<port-foward-port>
  am_lighthouse: false
  hosts:
  - 192.168.69.10
  - 192.168.69.11
  local_allow_list:
    interfaces:
      e.*: true
listen:
  host: 0.0.0.0
  port: <node_port>
logging:
  format: text
  level: warning
pki:
  ca: |
    -----BEGIN NEBULA CERTIFICATE-----
    -----END NEBULA CERTIFICATE-----
  cert: |
    -----BEGIN NEBULA CERTIFICATE-----
    -----END NEBULA CERTIFICATE-----
  key: |
    -----BEGIN NEBULA X25519 PRIVATE KEY-----
    -----END NEBULA X25519 PRIVATE KEY-----
preferred_ranges:
- 192.168.120.0/24
punchy:
  delay: 1s
  punch: true
  respond: true
relay:
  am_relay: false
  relays:
  - 192.168.69.10
  - 192.168.69.11
  use_relays: false
routines: 4
sshd:
  authorized_users:
  - keys:
    - <key>
    user: <user>
  enabled: true
  host_key: /<key-path>
  listen: 0.0.0.0:<another_port>
static_host_map:
  192.168.69.10:
  - <ip:<port>
  - <dns>:<port
  192.168.69.11:
  - <ip:<port>
  <OtherInternetHosts>:
  - <OtherInternetHosts>
static_map:
  network: ip4
tun:
  dev: nebula1
  disabled: false
  drop_local_broadcast: true
  drop_multicast: true
  mtu: 8800
  tx_queue: 500 


```
