### ISSUE TITLE
🐛 BUG: Unable to connect to lighthouse occasionally

### ISSUE THREAD

**Issue by TwoBirdsOnTheTree** [slackhq/nebula#1335]
### What version of `nebula` are you using? (`nebula -version`)

1.9.5 (all host)

### What operating system are you using?

Linux, Android

### Describe the Bug

Nebula host occasionally fails to connect to lighthouse (both Unraid NAS and andorid phone). like this:

![Image](https://github.com/user-attachments/assets/b451a096-53ab-46f3-9472-2fabfa5952c6)

After i restart nebula app (or switch network from wifi to cellular), nebula host connect to lighthouse successfully. like this:

![Image](https://github.com/user-attachments/assets/dbf5b4db-a868-48db-a244-02152acb75cd)

My nebula hosts and vpnIP:
- lighthouse: 192.168.100.100 
  - (also is relay host)
- unraid (Linux NAS): 192.168.100.1
- pc (Windows): 192.168.100.2
- k50 (Android phone): 192.168.100.3
- jdc-1 (remote router): 192.168.100.4
---
Besides this, i notice that lighthouse cann't listen both IPv4 and IPv6 address if listen address set to "[::]". like this:
``` shell
~#: lsof -i :62100
COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
nebula  4687 root    7u  IPv6  51294      0t0  UDP *:62100
```

### Logs from affected hosts

[LighthouseAndAndroidLogs.md](https://github.com/user-attachments/files/19067632/LighthouseAndAndroidLogs.md)

### Config files from affected hosts

Lighthouse (192.168.100.100) config.yml:
``` yaml
static_host_map:
  "192.168.100.100": ["xx.xxx.xx.xx:62100"]

static_map:
  network: ip

lighthouse:
  am_lighthouse: true

listen:
  # edit from "[::]"
  host: '0.0.0.0'
  port: 62100

punchy:
  punch: false
  respond: false

relay:
  # also as relay server
  am_relay: true
  use_relays: false

tun:
  disabled: false
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300

logging:
  level: debug
  format: text

firewall:
  outbound_action: drop
  inbound_action: drop
  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m
  outbound:
    - port: any
      proto: any
      host: any
  inbound:
    - port: any
      proto: any
      group: my_device
```
Android (192.168.100.3) config:
``` yaml
static_host_map:
  192.168.100.100:
  - xx.xxx.xx.xx:62100
lighthouse:
  am_lighthouse: false
  serve_dns: false
  dns:
    host: ""
    port: 0
  interval: 10
  hosts:
  - 192.168.100.100
listen:
  host: '[::]'
  port: 0
  batch: 64
  read_buffer: 0
  write_buffer: 0
punchy:
  punch: true
  respond: false
  delay: 1s
cipher: aes
local_range: ""
sshd:
  enabled: false
  listen: ""
  host_key: ""
  authorized_users: []
tun:
  dev: tun1
  drop_local_broadcast: true
  drop_multicast: true
  tx_queue: 500
  mtu: 1300
  routes: []
  unsafe_routes: []
logging:
  level: debug
  format: text
stats:
  type: ""
  interval: ""
  prefix: ""
  protocol: ""
  host: ""
  listen: ""
  path: ""
  namespace: ""
  subsystem: ""
handshakes:
  try_interval: 100ms
  retries: 20
  wait_rotation: 5
firewall:
  conntrack:
    tcp_timeout: 120h
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000
  outbound:
  - port: any
    proto: any
    host: any
  inbound: []
relay:
  use_relays: true
```

jdc-1 (192.168.100.4) config.yml (is similar with other host's config.yml):
``` yaml
static_host_map:
  "192.168.100.100": ["xx.xxx.xx.xx:62100"]

static_map:
  network: ip4

lighthouse:
  am_lighthouse: false
  interval: 10
  hosts:
    - "192.168.100.100"

listen:
  host: '[::]'
  port: 0

punchy:
  punch: true
  respond: true

relay:
  relays:
    - 192.168.100.100
  am_relay: false
  use_relays: true

tun:
  disabled: false
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300

logging:
  level: debug
  format: text

firewall:
  outbound_action: drop
  inbound_action: drop
  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m
  outbound:
    - port: any
      proto: any
      host: any
  inbound:
    - port: any
      proto: any
      group: my_device
```
