### ISSUE TITLE
🐛 BUG: relaying is broken

### ISSUE THREAD

**Issue by timteka** [slackhq/nebula#1355]
### What version of `nebula` are you using? (`nebula -version`)

1.9.5

### What operating system are you using?

Linux

### Describe the Bug

I've tried to set up k8s with three pods: -a, -b and -c. With -b as a relay for -a and -c. No success.

### Configs from affected hosts

```yml
# for -b pod
pki:
  ca: /etc/nebula/certs/ca.crt
  cert: /etc/nebula/certs/b.crt
  key: /etc/nebula/certs/b.key
static_host_map:
  "192.168.100.2": ["nebula-a.default.svc.cluster.local:4242"]
  "192.168.100.4": ["nebula-c.default.svc.cluster.local:4242"]
timeout: 30s
listen:
  host: 0.0.0.0
  port: 4242
punchy: true
relay:
  am_relay: true
  use_relays: false
tun:
  dev: nebula1
firewall:
  outbound:
  - port: any
    proto: any
    host: any
  inbound:
  - port: any
    proto: any
    host: any
logging:
  level: debug
```
and pod -a
```yml
pki:
  ca: /etc/nebula/certs/ca.crt
  cert: /etc/nebula/certs/a.crt
  key: /etc/nebula/certs/a.key
static_host_map:
  "192.168.100.3": ["nebula-b.default.svc.cluster.local:4242"]
timeout: 30s
listen:
  host: 0.0.0.0
  port: 4242
punchy: true
relay:
  relays:
    - "192.168.100.3"
  use_relays: true
tun:
  dev: nebula1
firewall:
  outbound:
  - port: any
    proto: any
    host: any
  inbound:
  - port: any
    proto: any
    host: any
```
and pod -c:
```yml
pki:
  ca: /etc/nebula/certs/ca.crt
  cert: /etc/nebula/certs/c.crt
  key: /etc/nebula/certs/c.key
static_host_map:
  "192.168.100.3": ["nebula-b.default.svc.cluster.local:4242"]
timeout: 30s
listen:
  host: 0.0.0.0
  port: 4242
punchy: true
relay:
  relays:
    - "192.168.100.3"
  use_relays: true
tun:
  dev: nebula1
firewall:
  outbound:
  - port: any
    proto: any
    host: any
  inbound:
  - port: any
    proto: any
    host: any
```

### Logs from affected hosts

```
-a can ping -b
-c can ping -b
-a can't ping -c
```
