### ISSUE TITLE
🐛 BUG: firewall blocks established UDP connection

### ISSUE THREAD

**Issue by Cyberes** [slackhq/nebula#1367]
### What version of `nebula` are you using? (`nebula -version`)

1.9.5

### What operating system are you using?

Linux <-> Windows

### Describe the Bug

I am using Nebula to connect to my Arma 3 game server (traffic is UDP). A game client is able to query and begin to join the server but it seems most traffic from the server to the client is getting blocked by the client's firewall and as a result the client cannot join the game server.

Adding a firewall rule like this fixes the problem and the client can connect:
```yaml
inbound:
  - port:  any
    proto: any
    host: any
```

Is there something odd going on here or is this the intended behavior?

### Logs from affected hosts

Client:
```
DEBU[0007] dropping inbound packet                       certName=windows_server_laptop fwPacket="&{172.0.15.1 172.0.3.3 0 0 17 true}" localIndex=898481496 reason="no matching rule in firewall table" remoteIndex=3417249616 vpnIp=172.0.3.3
DEBU[0007] dropping inbound packet                       certName=windows_server_laptop fwPacket="&{172.0.15.1 172.0.3.3 0 0 17 true}" localIndex=898481496 reason="no matching rule in firewall table" remoteIndex=3417249616 vpnIp=172.0.3.3
DEBU[0007] dropping inbound packet                       certName=windows_server_laptop fwPacket="&{172.0.15.1 172.0.3.3 0 0 17 true}" localIndex=898481496 reason="no matching rule in firewall table" remoteIndex=3417249616 vpnIp=172.0.3.3
DEBU[0007] dropping inbound packet                       certName=windows_server_laptop fwPacket="&{172.0.15.1 172.0.3.3 0 0 17 true}" localIndex=898481496 reason="no matching rule in firewall table" remoteIndex=3417249616 vpnIp=172.0.3.3
DEBU[0007] dropping inbound packet                       certName=windows_server_laptop fwPacket="&{172.0.15.1 172.0.3.3 0 0 17 true}" localIndex=898481496 reason="no matching rule in firewall table" remoteIndex=3417249616 vpnIp=172.0.3.3
DEBU[0007] dropping inbound packet                       certName=windows_server_laptop fwPacket="&{172.0.15.1 172.0.3.3 0 0 17 true}" localIndex=898481496 reason="no matching rule in firewall table" remoteIndex=3417249616 vpnIp=172.0.3.3
```

### Config files from affected hosts

```yaml
firewall:
  conntrack:
    default_timeout: 10m
    max_connections: 100000
    tcp_timeout: 12m
    udp_timeout: 3m
  inbound:
  - host: any
    port: any
    proto: icmp
    
    # This is the rule that fixes this problem
  - group: server
    port: any
    proto: any

  outbound:
  - host: any
    port: any
    proto: any
lighthouse:
  am_lighthouse: false
  hosts:
  - 172.0.0.2
  - 172.0.0.3
  interval: 60
listen:
  batch: 128
  host: 0.0.0.0
  port: 0
  read_buffer: 10485760
  write_buffer: 10485760
logging:
  format: text
  level: info
pki:
  ca: |
    -----BEGIN NEBULA CERTIFICATE-----
    xxx
    -----END NEBULA CERTIFICATE-----
  cert: |
    -----BEGIN NEBULA CERTIFICATE-----
    xxx
    -----END NEBULA CERTIFICATE-----
  key: |
    -----BEGIN NEBULA X25519 PRIVATE KEY-----
    xxx
    -----END NEBULA X25519 PRIVATE KEY-----
punchy:
  delay: 1s
  punch: true
  punch_back: true
  respond: true
relay:
  am_relay: false
  relays:
  - 172.0.0.2
  - 172.0.0.3
  use_relays: true
static_host_map:
  172.0.0.2:
  - xxx
  172.0.0.3:
  - xxx
tun:
  dev: nebula1
  disabled: false
  drop_local_broadcast: false
  drop_multicast: false
  routes: null
  tx_queue: 5000
  unsafe_routes: null
```
