### ISSUE TITLE
🐛 BUG: Only the most-recently-started of 2 Nebula processes can be pinged

### ISSUE THREAD

**Issue by nh2** [slackhq/nebula#1379]
### What version of `nebula` are you using? (`nebula -version`)

1.9.5

### What operating system are you using?

Linux

### Describe the Bug

When starting 2 Nebula processes ("1" and "1") with identical config (but different `listen.port`) on the same machine, from another machine I can only ping the one that was started last (most-recently).

## Full repro

* Process 1 has IP `10.52.0.6`
* Process 2 has IP `10.52.0.8`

Steps:

1. From a separate machine also in the same Nebula network, run `ping 10.52.0.6` and `10.52.0.7` to monitor which processes are reachable (none so far because we haven't started the processes yet). Then, on our repro machine:
2. Run `nebula -config nebula-config-1.yml` in one terminal.
  * The `ping 10.52.0.6` from above starts responding.
3. Run `nebula -config nebula-config-2.yml` in another terminal.
   * The `ping 10.52.0.8` from above starts responding.
   * But the `ping 10.52.0.6` from above **stops responding!**
4. Restart `nebula -config nebula-config-1.yml` from the first terminal.
   * The `ping 10.52.0.6` starts working again, but `ping 10.52.0.6` stops working agian.
5. We can cycle that forever.

Is there some undocumented shared resource between the two `tun` devices somehow?

Using `/nix/store/0qcb6prwzgf00526zh2snd5mb88d4mb9-nebula-1.9.5` from NixOS.

### Logs from affected hosts

When starting the second Nebula process that "breaks" the first one, no new logs are printed in the terminanl of the now-broken first one (at `INFO` level).

### Config files from affected hosts

`nebula-config-1.yml`

```yaml
firewall:
  inbound:
  - host: any
    port: any
    proto: icmp
  outbound:
  - host: any
    port: any
    proto: any
lighthouse:
  am_lighthouse: false
  hosts:
  - 10.52.0.7
  local_allow_list:
    ::/0: false
listen:
  host: '0.0.0.0'
  port: 4243
pki:
  ca: /etc/nixos/nebula/ca.crt
  cert: /etc/nixos/nebula/nh2.me.crt
  key: /etc/nixos/nebula/nh2.me.key
static_host_map:
  10.52.0.7:
  - 1.2.3.4:4242
tun:
  dev: nebula.nh2
  disabled: false
```

`nebula-config-2.yml`:

```yaml
firewall:
  inbound:
  - host: any
    port: any
    proto: icmp
  outbound:
  - host: any
    port: any
    proto: any
lighthouse:
  am_lighthouse: false
  hosts:
  - 10.52.0.7
  local_allow_list:
    ::/0: false
listen:
  host: '0.0.0.0'
  port: 4244
pki:
  ca: /etc/nixos/nebula-other/ca.crt
  cert: /etc/nixos/nebula-other/nh2.me-other.crt
  key: /etc/nixos/nebula-other/nh2.me-other.key
static_host_map:
  10.52.0.7:
  - 1.2.3.4:4242
tun:
  dev: nebula.nh2other
  disabled: false
```
