### ISSUE TITLE
🐛 BUG: Relay not working properly

### ISSUE THREAD

**Issue by MarkShamchinsky** [slackhq/nebula#1380]
### What version of `nebula` are you using? (`nebula -version`)

1.9.5

### What operating system are you using?

Linux

### Describe the Bug

I encountered a problem: if I restrict direct access between two servers through a firewall to make the traffic go through a relay, the servers won't connect. Neither ping nor traffic through iperf gets through. The relay logs show there is a handshake, but there is no data transfer between these two hosts.

### Logs from affected hosts

10.145.0.20
```
static_host_map:
  "10.145.0.1": ["158.160.94.127:42420"]
  "10.145.0.2": ["63.177.154.129:42420"]

lighthouse:
  am_lighthouse: false
  interval: 60
  hosts:
  - "10.145.0.1"
  - "10.145.0.2"

punchy:
  punch: true
  respond: false

relay:
  relays:
    - 10.145.0.23
  am_relay: false
  use_relays: true

tun:
  dev: nebula0

logging:
  level: debug
  format: text

stats:
  type: prometheus
  listen: 0.0.0.0:42421
  path: /metrics
  namespace: prometheusns
  subsystem: nebula
  interval: 10s



firewall:

  inbound_action: drop
  outbound_action: drop


  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10

  outbound:
    # Allow all outbound traffic from this node
    - port: any
      proto: any
      host: lighthousey
    - port: any
      proto: any
      host: lighthousef
    - port: any
      proto: any
      host: f1

  inbound:
    - port: any
      proto: any
      host: lighthousey
    - port: any
      proto: any
      host: lighthousef
    - port: any
      proto: any
      host: f1



```
10.145.0.19
```
static_host_map:
  "10.145.0.1": ["158.160.94.127:42420"]
  "10.145.0.2": ["63.177.154.129:42420"]

lighthouse:
  am_lighthouse: false
  interval: 60
  hosts:
  - "10.145.0.1"
  - "10.145.0.2"

punchy:
  punch: true
  respond: false

relay:
  relays:
    - 10.145.0.23
  am_relay: false
  use_relays: true

tun:
  dev: nebula0

logging:
  level: debug
  format: text

stats:
  type: prometheus
  listen: 0.0.0.0:42421
  path: /metrics
  namespace: prometheusns
  subsystem: nebula
  interval: 10s



firewall:

  inbound_action: drop
  outbound_action: drop


  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10

  outbound:
    # Allow all outbound traffic from this node
    - port: any
      proto: any
      host: lighthousey
    - port: any
      proto: any
      host: lighthousef
    - port: any
      proto: any
      host: f1

  inbound:
    - port: any
      proto: any
      host: lighthousey
    - port: any
      proto: any
      host: lighthousef
    - port: any
      proto: any
      host: f1



```
10.145.0.23 - relay (f1 host)
```
 static_host_map:
  "10.145.0.1": ["158.160.94.127:42420"]
  "10.145.0.2": ["63.177.154.129:42420"]
lighthouse:
  am_lighthouse: false
  interval: 60
  hosts:
    - "10.145.0.1"
    - "10.145.0.2"

punchy:
  punch: false
  respond: false

relay:
  am_relay: true

listen:
  host: 0.0.0.0
  port: 42420


tun:
  dev: nebula0

logging:
  level: info
  format: text

stats:
  type: prometheus
  listen: 0.0.0.0:42421
  path: /metrics
  namespace: prometheusns
  subsystem: nebula
  interval: 10s

firewall:
  outbound:
    - port: any
      proto: any
      host: any
  inbound:
    - port: any
      proto: any
      host: any

```

### Config files from affected hosts
relay log 
```
time="2025-04-07T13:16:15+03:00" level=info msg=handleCreateRelayRequest initiatorRelayIndex=3616641607 relayFrom=10.145.0.19 relayTo=10.145.0.20 vpnIp=10.145.0.19
time="2025-04-07T13:16:15+03:00" level=info msg="send CreateRelayRequest" initiatorRelayIndex=2528803272 relayFrom=10.145.0.19 relayTo=10.145.0.20 responderRelayIndex=0 vpnAddr=10.145.0.20
time="2025-04-07T13:16:15+03:00" level=info msg=handleCreateRelayResponse initiatorRelayIndex=2528803272 relayFrom=177274899 relayTo=177274900 responderRelayIndex=84167672 vpnIp=10.145.0.20

```
host  10.145.0.19 log, try to iperf 10.145.0.20
```
time="2025-04-07T13:23:08+03:00" level=debug msg="dropping outbound packet" certName=harbor fwPacket="&{10.145.0.19 10.145.0.20 45286 42421 6 false}" localIndex=1316053064 reason="no matching rule in firewall table" remoteIndex=833274357 vpnIp=10.145.0.20
time="2025-04-07T13:23:09+03:00" level=debug msg="dropping outbound packet" certName=harbor fwPacket="&{10.145.0.19 10.145.0.20 45286 42421 6 false}" localIndex=1316053064 reason="no matching rule in firewall table" remoteIndex=833274357 vpnIp=10.145.0.20

```
