### ISSUE TITLE
🐛 BUG: Handshake Timeout Between Nebula Nodes After Stage 2 (Lighthouse Responds, but Connection Fails)

### ISSUE THREAD

**Issue by jprrabanal** [slackhq/nebula#1420]
### What version of `nebula` are you using? (`nebula -version`)

1.9.5

### What operating system are you using?

Windows

### Describe the Bug

Windows node fails to complete the Nebula handshake after receiving a stage 2 response from the lighthouse. Handshake times out repeatedly, and the node cannot establish a full tunnel connection.

These are ping directions.
Ubuntu node (192.168.100.3) can ping Lighthouse (192.168.100.1)
Lighthouse (192.168.100.1) can ping Ubuntu (192.168.100.3)
Lighthouse can ping Windows (192.168.100.2)
Windows cannot ping Ubuntu (192.168.100.3)
Ubuntu cannot ping Windows (192.168.100.2)

Despite successful Stage 2 handshakes on both ends, traffic from/to the Windows node fails.
Windows node keeps attempting a handshake with 192.168.100.255.

I also disabled windows defender firewall when testing. Windows node directly connected to ISP router.

### Logs from affected hosts

```
time="2025-06-15T03:42:02+08:00" level=info msg="Firewall rule added" firewallRule="map[caName: caSha: direction:outgoing endPort:0 groups:[] host:any ip: localIp: proto:0 startPort:0]"
time="2025-06-15T03:42:02+08:00" level=info msg="Firewall started" firewallHashes="SHA:***,FNV:***"
2025/06/15 03:42:02 Using existing driver 0.14
2025/06/15 03:42:02 Creating adapter
time="2025-06-15T03:42:02+08:00" level=info msg="listening on 0.0.0.0:4242"
time="2025-06-15T03:42:02+08:00" level=info msg="Main HostMap created" network=192.168.100.2/24 preferredRanges="[]"
time="2025-06-15T03:42:02+08:00" level=info msg="punchy enabled"
time="2025-06-15T03:42:02+08:00" level=info msg="Loaded send_recv_error config" sendRecvError=always
time="2025-06-15T03:42:02+08:00" level=info msg="Nebula interface is active" boringcrypto=false build=1.9.5 interface=nebula1 network=192.168.100.2/24 udpAddr="0.0.0.0:4242"
time="2025-06-15T03:42:02+08:00" level=info msg="Handshake message sent" handshake="map[stage:1 style:ix_psk0]" initiatorIndex=4127866336 localIndex=4127866336 remoteIndex=0 udpAddrs="[*.*.*.*:4242]" vpnIp=192.168.100.1
time="2025-06-15T03:42:03+08:00" level=info msg="Handshake message received" certName=lighthouse durationNs=308865300 fingerprint=*** handshake="map[stage:2 style:ix_psk0]" initiatorIndex=4127866336 issuer=*** remoteIndex=4127866336 responderIndex=3133734007 sentCachedPackets=2 udpAddr="*.*.*.*:4242" vpnIp=192.168.100.1
time="2025-06-15T03:42:10+08:00" level=info msg="Handshake timed out" durationNs=7220210200 handshake="map[stage:1 style:ix_psk0]" initiatorIndex=3445824747 localIndex=3445824747 remoteIndex=0 udpAddrs="[]" vpnIp=192.168.100.255
time="2025-06-15T03:42:25+08:00" level=info msg="Handshake timed out" durationNs=7192987300 handshake="map[stage:1 style:ix_psk0]" initiatorIndex=3553235168 localIndex=3553235168 remoteIndex=0 udpAddrs="[]" vpnIp=192.168.100.255

```

### Config files from affected hosts

```
pki:
  ca: "C:\\path\\to\\ca.crt"
  cert: "C:\\path\\to\\win1.crt"
  key: "C:\\path\\to\\win1.key"

static_host_map:
  "192.168.100.1": ["<LIGHTHOUSE_PUBLIC_IP>:4242"]

lighthouse:
  am_lighthouse: false
  interval: 60
  hosts:
    - "192.168.100.1"

listen:
  host: 0.0.0.0
  port: 4242

firewall:
  outbound:
    - port: any
      proto: any
      host: any

tun:
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300

```

**Comment by nbrownus** [comment]
The logs you provided show that a tunnel between `192.168.100.2` and `192.168.100.1` was created. The config you provided does not allow for inbound `icmp` traffic though, which is likely the problem.

```
firewall:
  outbound:
    # Allow all outbound traffic from this node
    - port: any
      proto: any
      host: any

  inbound:
    # Allow icmp between any nebula hosts
    - port: any
      proto: icmp
      host: any
```

If the problem persists even after explicitly allowing the traffic in the nebula firewall then it's almost certainly the windows firewall getting in your way, setting the nebula network connection to "private network" should work.

The logs also show that a tunnel was unable to be completed for `192.168.100.255` which would be the broadcast address in your nebula network and is not expected to work. This is likely some automatic device discovery run by the OS.
