### ISSUE TITLE
Question: Uasge of unsafe_routes

### ISSUE THREAD

**Issue by mxalbert1996** [slackhq/nebula#214]
I have 2 machines, machine A as 192.168.2.1/24 and B as 192.168.2.2/24 in Nebula network.
I generated the cert of machine A by `nebula-cert sign -name "A" -ip "192.168.2.1/24" -subnets "192.168.1.0/24"`, and specified the following in the config of machine B:
```yaml
  unsafe_routes:
    - route: 192.168.1.0/24
      via: 192.168.2.1
```
However, I cannot access any nodes in the 192.168.1.0/24 subnet from machine B. Any ideas?

I noticed [this](https://github.com/slackhq/nebula/pull/119/files#diff-fc5059085a6bb53d00544fb7da80db2fR573) in the WIP documentation:
> The unsafe network segments in question, for
example 203.0.113.0/24 above, would also need to have a route back to the
nebula network (perhaps 203.0.113.2/24) which would need to be added as a
static route, or something the router in that subnet can direct.

What does this mean?

**Comment by nbrownus** [comment]
Are both machines running nebula? If so, you wouldn't need to expose them via `unsafe_routes`.

`unsafe_routes` is a way to declare a nebula exit node, that is to say, you send a packet from client A to server B and server B allows the decrypted packet to flow to the destination. If you expect client A to ever hear back from that destination then server B would need a route back to client A. This is can be handled with a NAT or with dedicated routes if you control the network at the destination.

**Comment by ChlorideCull** [comment]
First of all, machine A has to be configured to actually handle routing, otherwise it will drop the packets when they arrive.

As for what the documentation means, it says that devices on your `192.168.1.0/24` subnet has to have a route that lets them know that traffic to `192.168.2.0/24` should pass through machine A. You can push that to devices through DHCP, for example.

**Comment by sphr2k** [comment]
Hi,

maybe someone has an idea what I'm doing wrong.

* 2 nodes (1 lighthouse, 1 regular node for now)
* the lighthouse node connects to other networks using IPSec (vpnc) - these should be reachable from the other node(s)
* net.ipv4.ip_forward=1 on lighthouse node
* the lighthouse node's certificate contains the subnets
   ```
   NebulaCertificate {
        Details {
                Name: lighthouse
                Ips: [
                        10.11.0.1/24
                ]
                Subnets: [
                        10.0.6.0/24
                        10.10.0.0/16
                        10.12.0.0/16
                        192.168.1.0/24
                        192.168.37.0/24
                        192.168.123.0/24
                        192.168.222.0/24
   ```

* from regular node's config.yml:

  ```
    unsafe_routes:
    - route: 10.0.6.0/24
      via: 10.11.0.1
    - route: 10.10.0.0/16
      via: 10.11.0.1
    - route: 10.12.0.0/16
      via: 10.11.0.1
    - route: 192.168.1.0/24
      via: 10.11.0.1
    - route: 192.168.37.0/24
      via: 10.11.0.1
    - route: 192.168.123.0/24
      via: 10.11.0.1
    - route: 192.168.222.0/24
      via: 10.11.0.1
   ```
* on the regular node, routes are created correctly upon connection:
   ```
   WARN[0000] Adding UNSAFE Route                           route=10.0.6.0/24 via=10.11.0.1
WARN[0000] Adding UNSAFE Route                           route=10.10.0.0/16 via=10.11.0.1
WARN[0000] Adding UNSAFE Route                           route=10.12.0.0/16 via=10.11.0.1
WARN[0000] Adding UNSAFE Route                           route=192.168.1.0/24 via=10.11.0.1
WARN[0000] Adding UNSAFE Route                           route=192.168.37.0/24 via=10.11.0.1
WARN[0000] Adding UNSAFE Route                           route=192.168.123.0/24 via=10.11.0.1
WARN[0000] Adding UNSAFE Route                           route=192.168.222.0/24 via=10.11.0.1
  ```
* The tunnel works, i.e. ping from 10.11.0.2 to 10.11.0.1 or vice versa is OK, however unsafe subnets are not reachable
* I have a working setup using Wireguard to connect these servers, which is working fine

Am I missing something? Any help would be appreciated.

Thanks,
Jan
