### ISSUE TITLE
illegal Instruction on MerlinWRT armv7

### ISSUE THREAD

**Issue by OceanApart** [slackhq/nebula#222]
I have tried to execute the v1.2.0 [armv7](https://github.com/slackhq/nebula/releases/download/v1.2.0/nebula-linux-arm-7.tar.gz) binary on MerlinWRT armv7 architecture machine, but got an error message of "Illegal Instruction".

- ASUS AC-RT68U router running MerlinWRT 384.15

How should I got it work?

```yaml
# part of config
listen:
  host: 0.0.0.0
  port: 34242
  punch: true

  respond: true

cipher: chachapoly

tun:
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300
  routes:
  unsafe_routes:

firewall:
  conntrack:
    tcp_timeout: 120h
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000

  # The firewall is def
  outbound:
    # Allow all outbound traffic from this node
    - port: any
      proto: any
      host: any

  inbound:
    # Allow icmp between any nebula hosts
    - port: any
      proto: any
      host: any

    # Allow tcp/443 from any host with BOTH laptop and home group
    - port: 443
      proto: tcp
      groups:
        - laptop
        - home
```
