### ISSUE TITLE
weird, two nodes can't got connected

### ISSUE THREAD

**Issue by ghost** [slackhq/nebula#232]
background:

1 lighthouse  192.168.100.1
2 nodes in company: ubuntu 192.168.100.3, debian 192.168.100.6
1 node at home: mac 192.168.100.7

ubuntu and debian are using wired connection and under the same subnet

mac is using wifi.

situations:

1, when mac is at home

all nodes are connected to lighthouse
ubuntu can connect to all nodes: debian, mac
debian can connect to ubuntu but not mac
mac can connect to ubuntu but not debian

2,  take mac to company.

mac is the in the same subnet of ubuntu and debian.

mac can connect to all nodes.

---

one more thing, if mac performs self-ping 192.168.100.7 and no response at all. but it gets replies if ping with physical ip 192.168.10.55

here is the mac config.
```
pki:
  ca: ca-nebula.crt
  cert: mbp-nebula.crt
  key: mbp-nebula.key

static_host_map:
  "192.168.100.1": ["xxx:xxx"]

lighthouse:
  am_lighthouse: false
  interval: 60
  hosts:
    - "192.168.100.1"
  remote_allow_list:
    # Example to block IPs from this subnet from being used for remote IPs.
    "0.0.0.0/0": true
  local_allow_list:
    interfaces:
      en1: false
      en2: false
      en3: false
      en4: false
      bridge0: false
      utun0: false
      utun1: false
      en5: false
      lo0: false
      p2p0: false
      awdl0: false
      llw0: false
      gif0: false
      stf0: false

listen:
  host: 0.0.0.0
  port: 0

punchy:
  punch: true

tun:
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1500
logging:
  level: debug
  format: text

firewall:
  conntrack:
    tcp_timeout: 120h
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000
  outbound:
    - port: any
      proto: any
      host: any

  inbound:
    - port: any
      proto: any
      host: any
```

please let me know if you need more info. thanks!
