### ISSUE TITLE
How to connect a single node to 2 (or more) lighthouses belonging to different organizations?

### ISSUE THREAD

**Issue by stangri** [slackhq/nebula#235]
This is a continuation of this https://github.com/slackhq/nebula/issues/111#issuecomment-609749857 which got too off-topic for the original issue.

I have a node which needs to be connected to 2 lighthouses at the same time (I can juggle the config files of course, but I'd prefer the node to be connected to more than 1 lighthouse at the time).

The lighthouses have their own CAs and their own IP ranges. I have no problem combining two CA certificates in one file, however in my case the config.yml looks like:

```yml
static_host_map:
  "192.0.2.1": ["198.51.100.1:4242"]
  "192.0.3.1": ["203.0.113.30:4242"]
lighthouse:
  am_lighthouse: false
  interval: 60
  hosts:
    - "192.0.2.1"
    - "192.0.3.1"
```

If I comment out the ```192.0.3.1``` lines, everything works with a single (first) lighthouse, however as soon as I uncomment them, I get the error: ```FATA[0000] lighthouse host is not in our subnet, invalid  network=192.0.2.1/24 vpnIp=192.0.3.1```. Obviously I cannot use the same node certificate to connect to both as the host certificate has the IP assigned. I've tried combining both node certificates in one file, however that doesn't help. 

How can I establish connection to two different lighthouses at the same time? They two lighthouses do not need to have routing to each other, they belong to different organizations, think of them as the entry points of two different clients for the freelancer.
