### ISSUE TITLE
administrative sshd refused connection from nebula vpn network

### ISSUE THREAD

**Issue by ghostoy** [slackhq/nebula#243]
I enabled sshd on lighthouse by listening on nebula internal network ip: 172.31.1.1:2222 and added incoming firewall rule for vpn ips. **On the first boot of nebula service**, the connection coming from vpn ips, like 172.31.1.2, still got refused by the firewall. The workaround is just to **signal the nebula process to reload the configuration file without changing anything**. And everything works just fine.

**Comment by ghostoy** [comment]
Config for the lighthouse:
```yaml
# ... parts before sshd
# sshd can expose informational and administrative functions via ssh this is a
sshd:
  # Toggles the feature
  enabled: true
  # Host and port to listen on, port 22 is not allowed for your safety
  listen: 127.0.0.1:2222
  # A file containing the ssh host private key to use
  # A decent way to generate one: ssh-keygen -t ed25519 -f ssh_host_ed25519_key -N "" < /dev/null
  host_key: /etc/nebula/ssh_host_ed25519_key
  # A file containing a list of authorized public keys
  authorized_users:
    - user: lighthouse
      # keys can be an array of strings or single string
      keys:
        - "..."
# ... parts before firewall -> inbound
  inbound:
    # Allow icmp between any nebula hosts
    - port: any
      proto: icmp
      host: any

    # Allow tcp/443 from any host with BOTH laptop and home group
    - port: 443
      proto: tcp
      groups:
        - laptop
        - home

    - port: 2222
      proto: tcp
      groups:
        - ssh
```
