### ISSUE TITLE
Unable To Start Prometheus Stats Endpoint On Nebula IP Unless `0.0.0.0` Address Is Used

### ISSUE THREAD

**Issue by bonedaddy** [slackhq/nebula#314]
Attempting to start a nebula node that has enabled prometheus statistics to accept connections on the nebula node IP causes startup to fail with the error message `bind: cannot assign requested address`.  If you want to be able to have the prometheus endpoint accept connections on the nebula IP, then you need to set the listening address to `0.0.0.0` which is not desirable since this would then start a listener on all attached interfaces.

Example config:

```yaml
  type: prometheus
  listen: 0.0.0.0:8081
  path: /metrics
  namespace: prometheusns
  subsystem: nebula
  interval: 10s
```
