### ISSUE TITLE
Client to client can't connect

### ISSUE THREAD

**Issue by apinter** [slackhq/nebula#336]
Hi,

Seen a few support related questions here, but if this is not the appropriate place to ask do let me know please!
I have an issue where I have 3 clients and one lighthouse (Linode VPS). All clients and lighthouse are on v1.3.

Client1 is my computer at home.
Client2 is my computer in my rack at home on a separate network, but has the same external ip as the router they use is the same.
Client3 is a client somewhere in Italy.

On Nebula I can reach client2 from client1 and client1 from client2, but client3 is unreachable for all of the other clients and client3 can't make a connection to client1 and 2 either. The lighthouse can ping and reach all the clients. 
In the logs I can see when client3 is trying to make a connection. Can see it's external and local ip, but never get to connect for some reason and stuck at the handshake.
Had a similar problem with 1.0 and 1.1, but usually it just takes some time, about 20mins and all good. Had this problem now for 4 days straight :/ 
Any help would be much appreciated.

### Lighthouse config:
```
pki:
  ca: /etc/nebula-osdoc/ca.crt
  cert: /etc/nebula-osdoc/osd-beacon.crt
  key: /etc/nebula-osdoc/osd-beacon.key
static_host_map:
lighthouse:
  am_lighthouse: true
  interval: 60
  hosts:
listen:
  host: 0.0.0.0
  port: 4343
punchy: true
punch_back: true
cipher: chachapoly
local_range: "17.11.0.0/24"
tun:
  dev: nebula2
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300
  routes:
  unsafe_routes:
logging:
  level: info
  format: text
firewall:
  conntrack:
    tcp_timeout: 120h
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000
  outbound:
    - port: any
      proto: any
      host: any
  inbound:
    - port: any
      proto: icmp
      host: any
    - port: 443
      proto: tcp
      groups:
        - laptop
        - home
```

### Client1 config:
```
pki:
  ca: /etc/nebula/ca.crt
  cert: /etc/nebula/c1.crt
  key: /etc/nebula/c2.key
static_host_map:
  "17.11.0.1": ["[IP_ADDR_OF_LIGHTHOUSE]]:4343"]
lighthouse:
  am_lighthouse: false
  interval: 60
  hosts:
    - "17.11.0.1"
listen:
  host: 0.0.0.0
  port: 0
punchy: true
punch_back: true
cipher: chachapoly
local_range: "17.11.0.0/24"
tun:
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300
  routes:
  unsafe_routes:
logging:
  level: info
  format: text
firewall:
  conntrack:
    tcp_timeout: 120h
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000
  outbound:
    - port: any
      proto: any
      host: any
  inbound:
    - port: any
      proto: any
      host: any
```
### Client2 config:
```
pki:
  ca: /etc/nebula/ca.crt
  cert: /etc/nebula/c2.crt
  key: /etc/nebula/c2.key
static_host_map:
  "17.11.0.1": ["[IP_ADDR_OF_LIGHTHOUSE]]:4343"]
lighthouse:
  am_lighthouse: false
  interval: 60
  hosts:
    - "17.11.0.1"
listen:
  host: 0.0.0.0
  port: 4242
punchy: true
punch_back: true
cipher: chachapoly
local_range: "17.11.0.0/24"
tun:
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300
  routes:
  unsafe_routes:
logging:
  level: info
  format: text
firewall:
  conntrack:
    tcp_timeout: 120h
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000
  outbound:
    - port: any
      proto: any
      host: any
  inbound:
    - port: any
      proto: icmp
      host: any
    - port: 443
      proto: tcp
      groups:
        - laptop
        - home
```
### Client3 config:
```
pki:
  ca: /etc/nebula/ca.crt
  cert: /etc/nebula/c3.crt
  key: /etc/nebula/c3.key
static_host_map:
  "17.11.0.1": ["[IP_ADDR_OF_LIGHTHOUSE]]:4343"]
lighthouse:
  am_lighthouse: false
  interval: 60
  hosts:
    - "17.11.0.1"
listen:
  host: 0.0.0.0
  port: 0
punchy: true
punch_back: true
cipher: chachapoly
local_range: "17.11.0.0/24"
tun:
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300
  routes:
  unsafe_routes:
logging:
  level: info
  format: text
firewall:
  conntrack:
    tcp_timeout: 120h
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000
  outbound:
    - port: any
      proto: any
      host: any
  inbound:
    - port: any
      proto: icmp
      host: any
    - port: 443
      proto: tcp
      groups:
        - laptop
        - home
```
