### ISSUE TITLE
Client cannot ping lighthouse, docker

### ISSUE THREAD

**Issue by Derkades** [slackhq/nebula#337]
I am not able to get a node in one docker container (`10.131.0.100/24`) to ping a lighthouse node in another container (`10.131.0.1`), so:
```
root@5d2b42dfdf67:/data# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    (snip)
2: nebula: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1300 qdisc fq_codel state UNKNOWN group default qlen 500
    link/none 
    inet 10.131.0.100/24 scope global nebula
       valid_lft forever preferred_lft forever
2101: eth0@if2102: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:0a:c0:0f:42 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.192.15.66/26 brd 10.192.15.127 scope global eth0
       valid_lft forever preferred_lft forever
root@5d2b42dfdf67:/data# ping 10.131.0.1
PING 10.131.0.1 (10.131.0.1) 56(84) bytes of data.
(hangs)
```
or the other way around
```
root@mfsmaster:/data# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    (snip)
2: nebula: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1300 qdisc fq_codel state UNKNOWN group default qlen 500
    link/none 
    inet 10.131.0.1/24 scope global nebula
       valid_lft forever preferred_lft forever
2103: eth0@if2104: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:0a:c0:0f:02 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.192.15.2/26 brd 10.192.15.63 scope global eth0
       valid_lft forever preferred_lft forever
root@mfsmaster:/data# ping 10.131.0.100
PING 10.131.0.100 (10.131.0.100) 56(84) bytes of data.
(hangs)
```

I have spent the last 5 hours troubleshooting, I know I've probably missed something obvious but I can't figure out what it is. From other github issues I've gathered that this setup should work fine. If someone here could have a look at the config files I'd be very thankful. If you need more information please let me know

* Nebula network does not overlap with docker network or other internal network (docker is configured to use /26 pools of `10.192.0.0/11`)
* Lighthouse port is open in router/firewall
* Port forwarding the client and adding it to `static_host_map` as well did not solve the issue

<details>
<summary>docker-compose</summary>

```yaml
version: '2.4'

services:

  lighthouse:
    image: derkades/nebula:testing
    ports: ['26486:26486/udp']
    cap_add: ['net_admin']
    devices: ['/dev/net/tun:/dev/net/tun']
    volumes:
      - type: bind
        source: ./nebula_lighthouse
        target: /etc/nebula
    networks: [lighthouse]

  client:
    image: derkades/nebula:testing
    cap_add: ['net_admin']
    devices: ['/dev/net/tun:/dev/net/tun']
    volumes:
      - type: bind
        source: ./nebula_client
        target: /etc/nebula
    depends_on: [lighthouse]
    networks: [client]

networks:
  lighthouse:
  client:
```
</details>

<details>
<summary>Dockerfile (nothing special)</summary>

```Dockerfile
FROM alpine AS downloader

RUN wget https://github.com/slackhq/nebula/releases/download/v1.3.0/nebula-linux-amd64.tar.gz && \
    tar -xzf nebula-linux-amd64.tar.gz || true # For some reason tar command exits with exit code 1 but it works fine

# Cannot use alpine, nebula needs GNU libc
FROM ubuntu:20.04

RUN mkdir /data
WORKDIR /data

COPY --from=downloader /nebula /bin/nebula
COPY --from=downloader /nebula-cert /bin/nebula-cert

CMD ["nebula", "-config", "/etc/nebula/config.yaml"]
```
</details>

<details>
<summary>client config.yaml</summary>

```yaml
pki:
  ca: /etc/nebula/ca.crt
  cert: /etc/nebula/client.crt
  key: /etc/nebula/client.key

static_host_map:
  "10.131.0.1": ["mydomain:26486"]

listen:
  host: 0.0.0.0
  port: 0

punchy:
  punch: true

lighthouse:
  am_lighthouse: false
  interval: 30
  hosts:
    - '10.131.0.1'

tun:
  disabled: false
  dev: nebula
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300

firewall:
  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000

  outbound:
    - port: any
      proto: any
      host: any

  inbound:
    - port: any
      proto: any
      host: any
```
</details>

<details>
<summary>lighthouse config.yaml</summary>

```yaml
pki:
  ca: /etc/nebula/ca.crt
  cert: /etc/nebula/lighthouse.crt
  key: /etc/nebula/lighthouse.key

static_host_map:
  "10.131.0.1": ["mydomain:26486"]

lighthouse:
  am_lighthouse: true
  interval: 30

  hosts: []

listen:
  host: 0.0.0.0
  port: 26486

punchy:
  punch: true

tun:
  disabled: false
  dev: nebula
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300
  unsafe_routes:

firewall:
  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000

  outbound:
    - port: any
      proto: any
      host: any

  inbound:
    - port: any
      proto: any
      host: any
```
</details>

<details>
<summary>client log</summary>

It only shows "message sent" not "message received", is this normal?
```log
time="2020-11-16T16:02:22Z" level=info msg="Firewall rule added" firewallRule="map[caName: caSha: direction:outgoing endPort:0 groups:[] host:any ip: proto:0 startPort:0]"
time="2020-11-16T16:02:22Z" level=info msg="Firewall rule added" firewallRule="map[caName: caSha: direction:incoming endPort:0 groups:[] host:any ip: proto:0 startPort:0]"
time="2020-11-16T16:02:22Z" level=info msg="Firewall started" firewallHash=21716b47a7a140e448077fe66c31b4b42f232e996818d7dd1c6c4991e066dbdb
time="2020-11-16T16:02:22Z" level=info msg="Main HostMap created" network=10.131.0.100/24 preferredRanges="[]"
time="2020-11-16T16:02:22Z" level=info msg="UDP hole punching enabled"
time="2020-11-16T16:02:22Z" level=info msg="Nebula interface is active" build=1.3.0 interface=nebula network=10.131.0.100/24 udpAddr="0.0.0.0:26487"
time="2020-11-16T16:02:22Z" level=info msg="Handshake message sent" handshake="map[stage:1 style:ix_psk0]" initiatorIndex=1902636086 remoteIndex=0 udpAddr="my.ip:26486" vpnIp=10.131.0.1
time="2020-11-16T16:02:23Z" level=info msg="Handshake message sent" handshake="map[stage:1 style:ix_psk0]" initiatorIndex=1902636086 remoteIndex=0 udpAddr="my.ip:26486" vpnIp=10.131.0.1
time="2020-11-16T16:02:23Z" level=info msg="Handshake message sent" handshake="map[stage:1 style:ix_psk0]" initiatorIndex=1902636086 remoteIndex=0 udpAddr="my.ip:26486" vpnIp=10.131.0.1
time="2020-11-16T16:02:24Z" level=info msg="Handshake message sent" handshake="map[stage:1 style:ix_psk0]" initiatorIndex=1902636086 remoteIndex=0 udpAddr="my.ip:26486" vpnIp=10.131.0.1
time="2020-11-16T16:02:24Z" level=info msg="Handshake message sent" handshake="map[stage:1 style:ix_psk0]" initiatorIndex=1902636086 remoteIndex=0 udpAddr="my.ip:26486" vpnIp=10.131.0.1
time="2020-11-16T16:02:25Z" level=info msg="Handshake message sent" handshake="map[stage:1 style:ix_psk0]" initiatorIndex=1902636086 remoteIndex=0 udpAddr="my.ip:26486" vpnIp=10.131.0.1
time="2020-11-16T16:02:26Z" level=info msg="Handshake message sent" handshake="map[stage:1 style:ix_psk0]" initiatorIndex=1902636086 remoteIndex=0 udpAddr="my.ip:26486" vpnIp=10.131.0.1
time="2020-11-16T16:02:27Z" level=info msg="Handshake message sent" handshake="map[stage:1 style:ix_psk0]" initiatorIndex=1902636086 remoteIndex=0 udpAddr="my.ip:26486" vpnIp=10.131.0.1
time="2020-11-16T16:02:28Z" level=info msg="Handshake message sent" handshake="map[stage:1 style:ix_psk0]" initiatorIndex=1902636086 remoteIndex=0 udpAddr="my.ip:26486" vpnIp=10.131.0.1
```
</details>

<details>
<summary>lighthouse log</summary>

`10.0.1.254` is the default gateway
```log
time="2020-11-16T16:04:31Z" level=info msg="Firewall rule added" firewallRule="map[caName: caSha: direction:outgoing endPort:0 groups:[] host:any ip: proto:0 startPort:0]"
time="2020-11-16T16:04:31Z" level=info msg="Firewall rule added" firewallRule="map[caName: caSha: direction:incoming endPort:0 groups:[] host:any ip: proto:0 startPort:0]"
time="2020-11-16T16:04:31Z" level=info msg="Firewall started" firewallHash=21716b47a7a140e448077fe66c31b4b42f232e996818d7dd1c6c4991e066dbdb
time="2020-11-16T16:04:31Z" level=info msg="Main HostMap created" network=10.131.0.1/24 preferredRanges="[]"
time="2020-11-16T16:04:31Z" level=info msg="UDP hole punching enabled"
time="2020-11-16T16:04:31Z" level=info msg="Nebula interface is active" build=1.3.0 interface=nebula network=10.131.0.1/24 udpAddr="0.0.0.0:26486"
time="2020-11-16T16:04:31Z" level=info msg="Handshake message received" certName=chunk_robin_1 fingerprint=a8b72155a0cd06ecde07bab31d8cbfdcc27c9231c3f9d09562af1f22707eceae handshake="map[stage:1 style:ix_psk0]" initiatorIndex=3477944642 remoteIndex=0 responderIndex=0 udpAddr="10.0.1.254:11650" vpnIp=10.131.0.100
time="2020-11-16T16:04:31Z" level=info msg="Handshake message sent" certName=chunk_robin_1 fingerprint=a8b72155a0cd06ecde07bab31d8cbfdcc27c9231c3f9d09562af1f22707eceae handshake="map[stage:2 style:ix_psk0]" initiatorIndex=3477944642 remoteIndex=0 responderIndex=1230715052 udpAddr="10.0.1.254:11650" vpnIp=10.131.0.100
time="2020-11-16T16:04:33Z" level=info msg="Handshake message sent" cached=true handshake="map[stage:2 style:ix_psk0]" udpAddr="10.0.1.254:11650" vpnIp=10.131.0.100
time="2020-11-16T16:04:35Z" level=info msg="Handshake message received" certName=chunk_robin_1 fingerprint=a8b72155a0cd06ecde07bab31d8cbfdcc27c9231c3f9d09562af1f22707eceae handshake="map[stage:1 style:ix_psk0]" initiatorIndex=3477944642 remoteIndex=0 responderIndex=0 udpAddr="10.0.1.254:11650" vpnIp=10.131.0.100
time="2020-11-16T16:04:35Z" level=info msg="Handshake message sent" certName=chunk_robin_1 fingerprint=a8b72155a0cd06ecde07bab31d8cbfdcc27c9231c3f9d09562af1f22707eceae handshake="map[stage:2 style:ix_psk0]" initiatorIndex=3477944642 remoteIndex=0 responderIndex=2671008165 udpAddr="10.0.1.254:11650" vpnIp=10.131.0.100
time="2020-11-16T16:04:37Z" level=info msg="Handshake message sent" cached=true handshake="map[stage:2 style:ix_psk0]" udpAddr="10.0.1.254:11650" vpnIp=10.131.0.100
time="2020-11-16T16:04:39Z" level=info msg="Handshake message received" certName=chunk_robin_1 fingerprint=a8b72155a0cd06ecde07bab31d8cbfdcc27c9231c3f9d09562af1f22707eceae handshake="map[stage:1 style:ix_psk0]" initiatorIndex=3477944642 remoteIndex=0 responderIndex=0 udpAddr="10.0.1.254:11650" vpnIp=10.131.0.100
time="2020-11-16T16:04:39Z" level=info msg="Handshake message sent" certName=chunk_robin_1 fingerprint=a8b72155a0cd06ecde07bab31d8cbfdcc27c9231c3f9d09562af1f22707eceae handshake="map[stage:2 style:ix_psk0]" initiatorIndex=3477944642 remoteIndex=0 responderIndex=2914711756 udpAddr="10.0.1.254:11650" vpnIp=10.131.0.100
time="2020-11-16T16:04:41Z" level=info msg="Handshake message sent" cached=true handshake="map[stage:2 style:ix_psk0]" udpAddr="10.0.1.254:11650" vpnIp=10.131.0.100
```
</details>
