### ISSUE TITLE
Add unsafe_route metric / hop count

### ISSUE THREAD

**Issue by Mrc527** [slackhq/nebula#353]
Hello guys,

In my scenario, I've multiple nodes which could serve the same unsafe route.
Let's say, I want to access a TV on my local network and I've nebula nodes on my NAS and Router. Both on the same local network.

So, while being on the road, I could connect to the TV through the NAS or the Router. But since the NAS is more powerful, I get a better bandwidth if I go through it rather than the Router.

I would like to have an option in the unsafe_routes to specify a priority like:
```
unsafe_routes:
    - route: 192.168.1.0/24
      via: 192.168.99.1
      priority: 1
    - route: 192.168.1.0/24
      via: 192.168.99.2
      priority: 2
```

So, my nebula client should first try to reach 192.168.1.0 network through 192.168.99.1 and, if 192.168.99.1 is not reachable, start looking for 192.168.99.2.

How do you see it?

Ciao!
M
