### ISSUE TITLE
No NFS share between two nebula hosts

### ISSUE THREAD

**Issue by ccauet** [slackhq/nebula#358]
I have trouble setting up an NFS share between two nebula hosts, one acting as a server (`192.168.100.151`), one as a client (`192.168.100.152`).

Are there any known limitations that could explain this? 

Nebula config:

```
pki:
  ca: /etc/nebula/certs/ca.crt
  cert: /etc/nebula/certs/host.crt
  key: /etc/nebula/certs/host.key
  blocklist: []

static_host_map:
  "192.168.100.1": ["lighthouse1.example.com:4242", "IP1:4242"]
  "192.168.100.2": ["lighthouse2.example.com:4242", "IP2:4242"]

lighthouse:
  am_lighthouse: False

  hosts:
    - "192.168.100.1"
    - "192.168.100.2"

# Port Nebula will be listening on. The default here is 4242. For a lighthouse node, the port should be defined,
# however using port 0 will dynamically assign a port and is recommended for roaming nodes.
listen:
  host: 0.0.0.0
  port: 4242

punchy:
  # Continues to punch inbound/outbound at a regular interval to avoid expiration of firewall nat mappings
  punch: true
  respond: true

tun:
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300
  routes:
  unsafe_routes:

logging:
  level: info
  format: text

firewall:
  conntrack:
    tcp_timeout: 120h
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000

  outbound:
    # Allow all outbound traffic from this node
    - port: any
      proto: any
      host: any

  inbound:
    - port: any
      proto: any
      host: any
```

`/etc/exports` on server side

```
/mnt/nfs/data	*(rw,async,no_subtree_check)
```

Mounting directly via `sudo mount 192.168.100.151:/mnt/nfs/data /data` or just trying to `showmount -e 192.168.100.151` fail and result in hanging terminal.
