### ISSUE TITLE
disabling a user

### ISSUE THREAD

**Issue by hksk** [slackhq/nebula#376]
Hi guys, exists a way to disable a user after create and validate the connection?
my first thought is about recreate the lighthouse cert

**Comment by jimpea21** [comment]
I believe the certificate blocklist can be used for this. Depending on how extensive you need the block to be, you might be able to get away with just blocking the certificate of the offender at the lighthouse.

From the sample config at [https://github.com/slackhq/nebula/blob/master/examples/config.yml](https://github.com/slackhq/nebula/blob/master/examples/config.yml):

````
# PKI defines the location of credentials for this node. Each of these can also be inlined by using the yaml ": |" syntax.
pki:
  # The CAs that are accepted by this node. Must contain one or more certificates created by 'nebula-cert ca'
  ca: /etc/nebula/ca.crt
  cert: /etc/nebula/host.crt
  key: /etc/nebula/host.key
  #blocklist is a list of certificate fingerprints that we will refuse to talk to
  #blocklist:
  #  - c99d4e650533b92061b09918e838a5a0a6aaee21eed1d12fd937682865936c72
````

You can get the fingerprint using nebula-cert. Example below is Windows, but Linux should work the same:
````
C:\nebula>nebula-cert print -path jplaptop.crt
NebulaCertificate {
        Details {
                Name: jplaptop
                Ips: [
                        172.16.30.139/24
                ]
                Subnets: []
                Groups: []
                Not before: 2021-02-08 14:53:43 +0800 AWST
                Not After: 2022-02-01 16:27:16 +0800 AWST
                Is CA: false
                Issuer: ed119ff9415f3de48f65f7132670e52f8d4572043462d863d009ba38526fc13d
                Public key: 612ee48e835b1cdea6cc0d75f46dbc92311ff2e08e408f7a8c3a71bd2c767378
        }
        Fingerprint: d88333586a536bf2e9f59adacf1c24874d4d31a2aacbdea235c59051ced59fcc
        Signature: 6e223f5302b9d27c7ca40ad10c2746e794bc03e00d76cd0ce1b703e20499ff10e86730f45e1d0baf938ed68567b1dd1dda13439c631a6995f7170f7f8929930d
}

C:\nebula>
````

If the offender can't connect to the lighthouse, then it will be hard for them to locate the correct IP:PORT of the other nodes in the network to connect to in the first place (difficulty depends largely on your network layout).

If you need a 100% block then I guess you would need to block the offending certificate in the config of every single host, and / or adjust the Nebula firewall rules on every single VPN host so that they don't talk to the VPN IP of the offender (since each certificate is only valid for a specified IP). If you need to go this far then it might be easier to regenerate the CA and generate new certificates for all the valid hosts.
