### ISSUE TITLE
Fails to spin up prometheus stats endpoint on nebula interface

### ISSUE THREAD

**Issue by AndrewChubatiuk** [slackhq/nebula#393]
When trying to spin up prometheus metrics endpoint on nebula interface, it fails from time to time
My configuration is:
```
firewall:
    conntrack:
        default_timeout: 10m
        max_connections: 100000
        tcp_timeout: 120h
        udp_timeout: 3m
    inbound:
    -   host: any
        port: any
        proto: icmp
    -   host: any
        port: any
        proto: tcp
    -   host: any
        port: any
        proto: udp
    outbound:
    -   host: any
        port: any
        proto: any
lighthouse:
    am_lighthouse: false
    hosts:
    - 172.21.3.4
    - 172.21.3.5
    - 172.21.3.6
    interval: 60
listen:
    host: <node_public_ip>
    port: 4242
logging:
    format: json
    level: warning
pki:
    ca: /etc/nebula/ca.crt
    cert: /etc/nebula/prod-fsn1-kafka-1.crt
    key: /etc/nebula/prod-fsn1-kafka-1.key
static_host_map:
    172.21.3.4:
    - <lighthouse_1_address>:4242
    172.21.3.5:
    - <lighthouse_2_address>:4242
    172.21.3.6:
    - <lighthouse_3_address>:4242
stats:
    interval: 10s
    lighthouse_metrics: true
    listen: 172.21.3.24:8181
    message_metrics: true
    namespace: prometheusns
    path: /metrics
    subsystem: nebula
    type: prometheus
tun:
    dev: nebula1
    drop_local_broadcast: false
    drop_multicast: false
    mtu: 1300
    tx_queue: 500
```
