### ISSUE TITLE
Node in Synology DS918+ exits on start, no particular error

### ISSUE THREAD

**Issue by dgraziotin** [slackhq/nebula#432]
Hi, I have a network of several nodes and one lighthouse. 

Everything works well but the one in my Synology (LAN, at home). 

`nebula` exits and says goodbye. No other info shown. 
The node was working fine, but stopped working after I killed the app once.

I have other devices in the same LAN, all connect fine.

Here is a verbose run:

```
/volume1/homes/daniel/bin/nebula -config /volume1/homes/daniel/bin/config.yml
DEBU[0000] Trusted CA fingerprints                       fingerprints="[faa52b09fc74237691c2a6a706e383b1b07289c91241db7bb7434810dd092262]"
DEBU[0000] Client nebula certificate                     cert="NebulaCertificate {\n\tDetails {\n\t\tName: ds918+\n\t\tIps: [\n\t\t\t192.168.100.104/24\n\t\t]\n\t\tSubnets: []\n\t\tGroups: []\n\t\tNot before: 2021-03-22 11:53:19 +0100 CET\n\t\tNot After: 2031-03-19 19:02:34 +0100 CET\n\t\tIs CA: false\n\t\tIssuer: faa52b09fc74237691c2a6a706e383b1b07289c91241db7bb7434810dd092262\n\t\tPublic key: 34055b689c26e8d92e9470b052c7b4fa970e855d7863277924494c0e13bdcd53\n\t}\n\tFingerprint: 37c705c33a7c36122ea68d57e17392ccb2a978a3521964c1bfc8ebb655f5389b\n\tSignature: 2e3d1733e5e175640f02529710452e6158c3c74d53df1afb9c4ca33cbe3a119547c1a1633464c4c45c4c669df6a3df0456a213a5096c1a9e084a1fc1360e450a\n}"
INFO[0000] Firewall rule added                           firewallRule="map[caName: caSha: direction:outgoing endPort:0 groups:[] host:any ip: proto:0 startPort:0]"
INFO[0000] Firewall rule added                           firewallRule="map[caName: caSha: direction:incoming endPort:0 groups:[] host:any ip: proto:0 startPort:0]"
INFO[0000] Firewall started                              firewallHash=21716b47a7a140e448077fe66c31b4b42f232e996818d7dd1c6c4991e066dbdb
INFO[0000] Main HostMap created                          network=192.168.100.104/24 preferredRanges="[]"
INFO[0000] UDP hole punching enabled                    
DEBU[0000] remoteAllowList.Allow                         allow=true remoteIp="my.lighthouse.ip.redacted:4242"
DEBU[0000] localAllowList.AllowName                      allow=true interfaceName=lo
DEBU[0000] localAllowList.AllowName                      allow=true interfaceName=sit0
DEBU[0000] localAllowList.AllowName                      allow=true interfaceName=eth0
DEBU[0000] localAllowList.Allow                          allow=true localIp=192.168.178.3
DEBU[0000] localAllowList.AllowName                      allow=true interfaceName=eth1
DEBU[0000] localAllowList.Allow                          allow=true localIp=169.254.127.125
DEBU[0000] localAllowList.AllowName                      allow=true interfaceName=tailscale0
INFO[0000] Nebula interface is active                    build=1.3.0 interface=neb0 network=192.168.100.104/24 udpAddr="0.0.0.0:4242"
DEBU[0000] localAllowList.Allow                          allow=true localIp=100.87.160.74
DEBU[0000] localAllowList.AllowName                      allow=true interfaceName=docker-fc0c3cae
DEBU[0000] localAllowList.Allow                          allow=true localIp=192.168.48.1
DEBU[0000] localAllowList.AllowName                      allow=true interfaceName=docker-5f309c5d
DEBU[0000] localAllowList.Allow                          allow=true localIp=172.20.0.1
DEBU[0000] localAllowList.AllowName                      allow=true interfaceName=docker-76b5a4c2
DEBU[0000] localAllowList.Allow                          allow=true localIp=172.23.0.1
DEBU[0000] localAllowList.AllowName                      allow=true interfaceName=docker-76c9af91
DEBU[0000] localAllowList.Allow                          allow=true localIp=192.168.144.1
DEBU[0000] localAllowList.AllowName                      allow=true interfaceName=docker-8625db13
DEBU[0000] localAllowList.Allow                          allow=true localIp=192.168.112.1
DEBU[0000] localAllowList.AllowName                      allow=true interfaceName=docker-c051fb16
DEBU[0000] localAllowList.Allow                          allow=true localIp=172.19.0.1
DEBU[0000] localAllowList.AllowName                      allow=true interfaceName=docker-ede07e17
DEBU[0000] localAllowList.Allow                          allow=true localIp=172.18.0.1
DEBU[0000] localAllowList.AllowName                      allow=true interfaceName=docker-65f5c08d
DEBU[0000] localAllowList.Allow                          allow=true localIp=192.168.224.1
DEBU[0000] localAllowList.AllowName                      allow=true interfaceName=docker-b059adbe
DEBU[0000] localAllowList.Allow                          allow=true localIp=172.21.0.1
DEBU[0000] localAllowList.AllowName                      allow=true interfaceName=docker0
DEBU[0000] localAllowList.Allow                          allow=true localIp=172.17.0.1
DEBU[0000] localAllowList.AllowName                      allow=true interfaceName=docker-f00557a2
DEBU[0000] localAllowList.Allow                          allow=true localIp=192.168.96.1
DEBU[0000] localAllowList.AllowName                      allow=true interfaceName=docker5fd9e10
DEBU[0000] localAllowList.AllowName                      allow=true interfaceName=docker19eda7b
DEBU[0000] localAllowList.AllowName                      allow=true interfaceName=docker0e4cce2
DEBU[0000] localAllowList.AllowName                      allow=true interfaceName=dockerfee1d1b
DEBU[0000] localAllowList.AllowName                      allow=true interfaceName=docker742be28
DEBU[0000] localAllowList.AllowName                      allow=true interfaceName=dockerccf6a29
DEBU[0000] localAllowList.AllowName                      allow=true interfaceName=docker455ca4d
DEBU[0000] localAllowList.AllowName                      allow=true interfaceName=docker127cbac
DEBU[0000] localAllowList.AllowName                      allow=true interfaceName=dockera92fe82
DEBU[0000] localAllowList.AllowName                      allow=true interfaceName=docker97ab5c5
DEBU[0000] localAllowList.AllowName                      allow=true interfaceName=dockerdd0bbd8
DEBU[0000] localAllowList.AllowName                      allow=true interfaceName=docker5fe5f80
DEBU[0000] localAllowList.AllowName                      allow=true interfaceName=docker6a5248f
DEBU[0000] localAllowList.AllowName                      allow=true interfaceName=docker-4c9b8621
DEBU[0000] localAllowList.Allow                          allow=true localIp=172.27.0.1
DEBU[0000] localAllowList.AllowName                      allow=true interfaceName=dockeracff91a
DEBU[0000] localAllowList.AllowName                      allow=true interfaceName=dockerf683b44
DEBU[0000] localAllowList.AllowName                      allow=true interfaceName=docker3a8d0dd
DEBU[0000] localAllowList.AllowName                      allow=true interfaceName=docker7caf3d7
DEBU[0000] localAllowList.AllowName                      allow=true interfaceName=docker15d6a74
DEBU[0000] localAllowList.AllowName                      allow=true interfaceName=docker1fea17d
DEBU[0000] localAllowList.AllowName                      allow=true interfaceName=dockerbb10058
DEBU[0000] localAllowList.AllowName                      allow=true interfaceName=dockerd06e1fe
DEBU[0000] localAllowList.AllowName                      allow=true interfaceName=neb0
DEBU[0000] localAllowList.Allow                          allow=true localIp=192.168.100.104
DEBU[0000] Generated index                               index=3114578665
DEBU[0000] Packet store                                  length=1 stored=true vpnIp=192.168.100.1
DEBU[0000] HandshakeManager: triggered                   vpnIp=192.168.100.1
INFO[0000] Handshake message sent                        handshake="map[stage:1 style:ix_psk0]" initiatorIndex=3114578665 remoteIndex=0 udpAddr="my.lighthouse.ip.redacted:4242" vpnIp=192.168.100.1
INFO[0000] Handshake message received                    certName=my.lighthouse.redacted durationNs=33674532 fingerprint=d9854e4fff5564f28009b5d36e5ca46c78be28973595577d4d29c17c548ea77e handshake="map[stage:2 style:ix_psk0]" initiatorIndex=3114578665 remoteIndex=3114578665 responderIndex=3360040103 udpAddr="my.lighthouse.ip.redacted:4242" vpnIp=192.168.100.1
DEBU[0000] Hostmap remote ip added                       hostMap="map[mapName:main mapTotalSize:1 udpAddr:my.lighthouse.ip.redacted:4242 vpnIp:192.168.100.1]"
DEBU[0000] Sending 1 stored packets                      certName=my.lighthouse.redacted vpnIp=192.168.100.1
DEBU[0000] Hostmap vpnIp deleted                         hostMap="map[mapName:pending mapTotalSize:0 vpnIp:192.168.100.1]"
DEBU[0000] Hostmap index deleted                         hostMap="map[indexNumber:3114578665 mapName:pending mapTotalSize:0]"
INFO[0001] Caught signal, shutting down                  signal=terminated
DEBU[0001] Sending close tunnel message                  udpAddr="my.lighthouse.ip.redacted:4242" vpnIp=192.168.100.1
INFO[0001] Goodbye 
```

Here is what the lighthouse logs:

```
Apr 01 14:05:21 my.lighthouse.redacted nebula[352885]: time="2021-04-01T14:05:21+02:00" level=info msg="Close tunnel received, tearing down." certName=ds918+ udpAddr="my.home.ip.redacted:61184" vpnIp=192.168.100.104
Apr 01 14:05:23 my.lighthouse.redacted nebula[352885]: time="2021-04-01T14:05:23+02:00" level=info msg="Handshake message received" certName=ds918+ fingerprint=37c705c33a7c36122ea68d57e17392ccb2a978a3521964c1bfc8ebb>
Apr 01 14:05:23 my.lighthouse.redacted nebula[352885]: time="2021-04-01T14:05:23+02:00" level=info msg="Handshake message sent" certName=ds918+ fingerprint=37c705c33a7c36122ea68d57e17392ccb2a978a3521964c1bfc8ebb655f>
Apr 01 14:05:24 my.lighthouse.redacted nebula[352885]: time="2021-04-01T14:05:24+02:00" level=info msg="Close tunnel received, tearing down." certName=ds918+ udpAddr="my.home.ip.redacted:61184" vpnIp=192.168.100.104
```
Here is config.yml (same config for all nodes)

```
pki:
  # every node needs a copy of the CA certificate,
  # and its own certificate and key, ONLY.
  #
  ca: /volume1/homes/daniel/bin/ca.crt
  cert: /volume1/homes/daniel/bin/ds918+.crt
  key: /volume1/homes/daniel/bin/ds918+.key

static_host_map:
 # how to find one or more lighthouse nodes
 # you do NOT need every node to be listed here!
 #
 # format "Nebula IP": ["public IP or hostname:port"]
 #
 "192.168.100.1": ["my.lighthouse.redacted:4242"]

lighthouse:
  interval: 60

  # if you're a lighthouse, say you're a lighthouse
  #
  am_lighthouse: false

  hosts:
    # If you're a lighthouse, this section should be EMPTY
    # or commented out. If you're NOT a lighthouse, list
    # lighthouse nodes here, one per line, in the following
    # format:
    #
    - "192.168.100.1"

listen:
  # 0.0.0.0 means "all interfaces," which is probably what you want
  #
  host: 0.0.0.0
  port: 4242

# "punchy" basically means "send frequent keepalive packets"
# so that your router won't expire and close your NAT tunnels.
#
punchy: true

# "punch_back" allows the other node to try punching out to you,
# if you're having trouble punching out to it. Useful for stubborn
# networks with symmetric NAT, etc.
#
punch_back: true

tun:
  # sensible defaults. don't monkey with these unless
  # you're CERTAIN you know what you're doing.
  #
  dev: neb0
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300
  routes:

logging:
  level: debug
  format: text

# you NEED this firewall section.
#
# Nebula has its own firewall in addition to anything
# your system has in place, and it's all default deny.
#
# So if you don't specify some rules here, you'll drop
# all traffic, and curse and wonder why you can't ping
# one node from another.
#
firewall:
  conntrack:
    tcp_timeout: 120h
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000

# since everything is default deny, all rules you
# actually SPECIFY here are allow rules.
#
  outbound:
    - port: any
      proto: any
      host: any

  inbound:
    - port: any
      proto: any
      host: any
```

I have no firewall running on either lighthouse or node.

This is the lighthouse config.yml

```
pki:
  # every node needs a copy of ca.crt, <client-name>.key,
  # and <client-name>.crt
  ca: /opt/nebula/ca.crt
  cert: /opt/nebula/my.lighthouse.redacted.crt
  key: /opt/nebula/my.lighthouse.redacted.key

static_host_map:
 # how to find one or more lighthouse nodes
 # you do NOT need every node to be listed here!
 # Similar to "trackers" for torrents
 #
 # format "<internal-nebula-ip-addr>": ["<pub-ip-addr>:[port] or <hostname>:[port]"]
 #
 "192.168.100.1": ["my.lighthouse.redacted:4242"]

lighthouse:
  interval: 60

  # if you're a lighthouse, say you're a lighthouse
  #
  am_lighthouse: true

  hosts:
    # If you're a lighthouse, this section should be EMPTY
    # or commented out. If you're NOT a lighthouse, list
    # lighthouse nodes here, one per line, in the following
    # format:
    #
    # - "192.168.77.1"

listen:
  # 0.0.0.0 means "all interfaces," which is probably what you want
  #
  host: 0.0.0.0
  port: 4242

# "punchy" basically means "send frequent keepalive packets"
# so that your router won't expire and close your NAT tunnels.
#
punchy: true

# "punch_back" allows the other node to try punching out to you,
# if you're having trouble punching out to it. Useful for stubborn
# networks with symmetric NAT, etc.
#
punch_back: true

tun:
  # sensible defaults. don't monkey with these unless
  # you're CERTAIN you know what you're doing.
  #
  dev: neb0
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300
  routes:

logging:
  level: info
  format: text

# you NEED this firewall section.
#
# Nebula has its own firewall in addition to anything
# your system has in place, and it's all default deny.
#
# So if you don't specify some rules here, you'll drop
# all traffic, and curse and wonder why you can't ping
# one node from another.
#
firewall:
  conntrack:
    tcp_timeout: 120h
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000

# since everything is default deny, all rules you
# actually SPECIFY here are allow rules.
#
  outbound:
    - port: any
      proto: any
      host: any

  inbound:
    - port: any
      proto: any
      host: any
```

I would appreciate any help!
