### ISSUE TITLE
reason="local IP is not in list of handled local IPs"

### ISSUE THREAD

**Issue by whyarenousernamesavailable** [slackhq/nebula#524]
I currently have 3 nodes setup like the diagram below. 
![Network Diagram](https://user-images.githubusercontent.com/90665611/133185167-7341567b-2bad-40af-b649-1f892384606f.png)
All three routers can ping all the nebula ips. All the machines behind the each of the routers can ping the nebula IP of the router they are behind. However none of the machines can ping the nebula IP of any other routers or any machines behind the other routers.

Example when trying to ping 172.19.1.1 from machine C, the output from nebula on the router (172.19.1.3) shows the following error. 
DEBU[0022] dropping outbound packet                      certName=my.hostname.org fwPacket="&{2886731002 2886926593 0 0 1 false}" reason="local IP is not in list of handled local IPs" vpnIp=172.19.1.1

Each node had the corresponding subnet included when generating the certificates. I had this working at some point before but cannot for the life of me get it to work again, What am i missing?

```
pki:
  ca: /etc/nebula/ca.crt
  cert: /etc/nebula/mycert.crt
  key: /etc/nebula/mykey.key

static_host_map:
 "172.19.1.1": ["lighthouse1.mydomain.org:4242"]
 "172.19.1.2": ["lighthouse2.mydomain.org:4242"]

lighthouse:
  interval: 60

  am_lighthouse: false
  
  hosts:
  - "172.19.1.1"
  - "172.19.1.2"
  
listen:
  host: 0.0.0.0
  port: 4242

punchy: true

punch_back: true

tun:
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300
  routes:
  unsafe_routes:
    - route: 172.16.0.0/16
      via: 172.19.1.3
    - route: 172.18.0.0/16
      via: 172.19.1.1
    - route: 172.17.0.0/16
      via: 172.19.1.2

logging:
  level: debug
  format: text

firewall:
  conntrack:
    tcp_timeout: 120h
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000

  outbound:
    - port: any
      proto: any
      host: any

  inbound:
    - port: any
      proto: any
      host: any
```
