### ISSUE TITLE
Peer can not reach each other peer when they can reach Lighthouse

### ISSUE THREAD

**Issue by op69qs** [slackhq/nebula#525]
All my pear can success to connect  Lighthouse  but they can not reach each other, Please help me out, thx.
```
Lighthouse Node 1: 192.168.16.1
pear01: 192.168.16.10
pear02: 192.168.16.50
```
<details>
<summary>Lighthouse config</summary>

```yaml
pki:
  ca: ca.crt
  cert: crt.crt
  key: key.key

static_host_map:
  "10.100.0.2": ["xxx:4242"]

lighthouse:
  am_lighthouse: true
  interval: 60
listen:
  host: 0.0.0.0
  port: 4242

punchy:
  punch: true

  respond: true

simultaneously!
cipher: chachapoly



tun:
  disabled: false
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300
  routes:


logging:
  level: info
  format: text


firewall:
  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000
  outbound:
    - port: any
      proto: any
      host: any

  inbound:
    - port: any
      proto: any
      host: any
```

</details>

<details>
<summary>peer config</summary>

```yaml


pki:
  ca: ca.crt
  cert: p.crt
  key: p.key

static_host_map:
  "10.100.0.2": ["xxx:4242"]


lighthouse:
  am_lighthouse: false
  interval: 60
  hosts:
    - "10.100.0.2"

listen:
  host: 0.0.0.0
  port: 4242

punchy:
  punch: true

  respond: true


cipher: chachapoly

tun:
  disabled: false
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300
  routes:
  unsafe_routes:
    - route: 192.168.123.0/24
      via: 10.100.0.10
    - route: 192.168.1.0/24
      via: 10.100.0.10
    - route: 192.168.125.0/24
      via: 10.100.0.11
    - route: 192.168.126.0/24
      via: 10.100.0.12
    - route: 192.168.124.0/24
      via: 10.100.0.13
logging:
  level: info
  format: text
firewall:
  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000
  outbound:
    - port: any
      proto: any
      host: any

  inbound:
    - port: any
      proto: any
      host: any

```

</details>
