### ISSUE TITLE
Question: LXD Bridge Setup

### ISSUE THREAD

**Issue by nfam** [slackhq/nebula#54]
I have Ubuntu homelab server with LXD enabled. My setup includes:
- 1 DO lighthouse (nebula IP 192.168.16.1)
- 1 Macbook (nebula IP 192.168.16.10)
- 1 physical Ubuntu 18.04 server (nebula IP 192.168.16.2)
- 1 LXD Ubuntu 18.04 server (LXD container) inside the above physical server (nebula IP 192.168.16.3)

My physical Ubuntu server has 3 interfaces: `enp2s0` (physical, bridge mode),`lanbr0` (bridge to `enp2s0`), and ` lxdbr0` (bridge for LXD internal network). The physical NIC `enp2s0` has been set to bridge mode as following netplan config
```yml
network:
    version: 2
    renderer: networkd
    ethernets:
        enp2s0:
            dhcp4: no
    bridges:
        lanbr0:
            interfaces: [enp2s0]
            macaddress: (same MAC address as the physical enp2s0)
            dhcp4: true
            parameters:
                stp: false
                forward-delay: 0
```
The LXD Ubuntu 18.04 server (LXD container) has 2 interfaces: `eth0` (bridged to parent `lxdbr0`), and `eth1` (bridged to parent `lanbr0`). Since this LXD container is bridged to `lanbr0`, it is visible to my physical homelab LAN.

When my MacBook is in the homelab LAN, I can use nebula to access to both physical server and LXD container.

But when I am in another house (100m away from my homelab, but both connected to the same ISP through fibre cable), my MacBook can ping (and ssh) to the physical server ( `192.168.16.2`), but cannot see the lxd container (`192.168.16.3`).

Should I need make any change on my LXD in order to access my LXD container when away from my homelab?
