### ISSUE TITLE
Performance and Tuning

### ISSUE THREAD

**Issue by frankyyy02** [slackhq/nebula#623]
Firstly, have to start with... this is an awesome project! Known of it for a couple of years maybe and finally got around to spinning it up.  

Looking for some guidance/advice.
Have setup a simple proof of concept to test some performance metrics.

Have a lighthouse configured on Proxmox with 4 CPUs, 2GB RAM and AES CPU flag enabled.  An Intel (Lenovo X1 Extreme) laptop also configured, all connected and working as expected.  Configuration is based on the example configuration file, only changing the lighthouse and adding a firewall allow rule for 5201 and 22.  Everything else as per the configuration file.

I then run `iperf` between the two across a 1Gb LAN.  For completeness, across the LAN file transfers via `scp` and `iperf` reflect a near 1Gb connection.

Running in `chachapoly` mode, I am seeing ~ 60MB/sec approximately with `iperf`.  No tweaks to other config settings outside of basic lighthouse/client setup.  This is about the same irrespective of when applying `-w 64KB` and `-P 4` command line options.

When i move from `chachapoly` to `aes`, expecting to see an increase, i see a decrease to approximately 43MB/sec.  I can confirm via `/proc/cpuinfo` that both have aes flags enabled.

I then increase MTU to 8k, and from the default, with `chachapoly` i can see about ~90MB/sec.  This is great.

Switching across to `aes` with 8k MTU, back down to 58MB/sec.

I suspect given the laptop may be roaming between sites/locations, the 8K MTU is probably less useful in those cases.

While I am quite happy with `chachapoly` at 8K MTU internally, i would of expected `aes` to exceed this based on my reading? Could be incorrect though.  It looks like i'm missing something here, but keen to hear from others.  What else should I be looking at here?

Appreciate any insight.

Client:

```
pki:
  ca: /home/test/nebula/home/ca.crt
  cert: /home/test/nebula/home/x1x2.crt
  key: /home/test/nebula/home/x1x2.key
static_host_map:
  "192.168.171.1": ["fqdn:4242"]
lighthouse:
  am_lighthouse: false
  interval: 60
  hosts:
    - "192.168.171.1"
listen:
  host: 0.0.0.0
  port: 4242
punchy:
  punch: true
cipher: aes
tun:
  disabled: false
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 8000
  routes:
  unsafe_routes:
logging:
  level: info
  format: text
firewall:
  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000
  outbound:
    - port: any
      proto: any
      host: any
  inbound:
    - port: any
      proto: icmp
      host: any
```

Lighthouse:

```
pki:
  ca: /opt/nebula/ca.crt
  cert: /opt/nebula/lighthouse1.crt
  key: /opt/nebula/lighthouse1.key
static_host_map:
        "192.168.171.1": ["fqdn:4242"]
lighthouse:
  am_lighthouse: true
  interval: 60
listen:
  host: 0.0.0.0
  port: 4242
punchy:
  punch: true
cipher: aes
tun:
  disabled: false
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 8000
  routes:
  unsafe_routes:
logging:
  level: info
  format: text
firewall:
  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000
  outbound:
    - port: any
      proto: any
      host: any
  inbound:
    - port: any
      proto: icmp
      host: any
    - port: 5201
      proto: tcp
      groups:
        - x1x2
    - port: 22
      proto: tcp
      groups:
        - x1x2
```
