### ISSUE TITLE
Android app - internal firewall settings

### ISSUE THREAD

**Issue by ajuitar** [slackhq/nebula#628]
Is there a way to edit the nebula internal firewall settings in the Android app? The default setting are:
```
firewall:
  conntrack:
    tcp_timeout: 120h
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000
  outbound:
  - port: any
    proto: any
    host: any
  inbound: []
```
and nothing much comes in.
