### ISSUE TITLE
dns domain

### ISSUE THREAD

**Issue by tcurdt** [slackhq/nebula#629]
How do I provide a domain so the name of the node becomes `node.internal` instead of just `node`

```
serve_dns: true
  dns:
    host: 0.0.0.0
    port: 53
```
