### ISSUE TITLE
msg="dropping outbound packet"

### ISSUE THREAD

**Issue by villain** [slackhq/nebula#64]
i have nebula setup, all hosts talking to each other, no communication issues it would seem. im attempting to use nebula to replace a gre tunnel setup, with the following iptables config:

```
sysctl -w net.ipv4.ip_forward=1

iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT
iptables -t nat -F
iptables -t mangle -F
iptables -F
iptables -X

iptables -t nat -I PREROUTING -p tcp --match multiport ! --dports 22 -j DNAT --to-destination 10.50.0.1:65535
iptables -t nat -I PREROUTING 1 -j LOG --log-prefix "[netfilter]: " --log-level 7
```

but when doing so, i receive a message from nebula in /var/log/syslog:

```
Dec  4 09:11:11 node-01 kernel: [41774.774651] [netfilter]: IN=eno1 OUT= MAC=94:c6:91:af:31:4d:00:c1:64:1f:dd:ba:08:00 SRC=185.176.27.30 DST=x.x.x.x LEN=40 TOS=0x00 PREC=0x40 TTL=247 ID=50880 PROTO=TCP SPT=54435 DPT=7196 WINDOW=1024 RES=0x00 SYN URGP=0 
Dec  4 09:11:11 node-01 nebula[1664]: time="2019-12-04T09:11:11+11:00" level=debug msg="dropping outbound packet" fwPacket="&{3115326238 171048961 54435 65535 6 false}" vpnIp=10.50.0.1
```

relevant part of the config file:

```
firewall:
  conntrack:
    tcp_timeout: 120h
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000

  outbound:
    # Allow all outbound traffic from this node
    - port: any
      proto: any
      host: any

  inbound:
    # Allow all inbound traffic
    - port: any
      proto: any
      host: any
```

this works fine with other setups (gre, openvpn, etc), and i'd like to know if there's a way to allow this in nebula
