### ISSUE TITLE
sshd command

### ISSUE THREAD

**Issue by irani74** [slackhq/nebula#640]
Hi,
I need to get a list of all clients connected to a Nebula network.
after reading issues, found #545 that answer my question
but I don't know how to run sshd in my CLI
Can anybody help me?

**Comment by theblop** [comment]
- generate a nebula ssh server key on the lighthouse:
```
cd /etc/nebula
ssh-keygen -t ed25519 -f ssh_host_ed25519_key -N "" < /dev/null
```

- generate a client key/pubkey:
```
ssh-keygen -f ssh_user.key
```

- configure sshd in the lighthouse's config.yaml:
```
sshd:
  enabled: true
  listen: 127.0.0.1:12222
  # A file containing the ssh host private key to use
  # A decent way to generate one: ssh-keygen -t ed25519 -f ssh_host_ed25519_key -N "" < /dev/null
  host_key: /etc/nebula/ssh_host_ed25519_key
  # A file containing a list of authorized public keys
  authorized_users:
    - user: root
      keys:
        # copy/paste the content of ssh_user.key.pub:
        - "ssh-rsa XXXXXXXXXXXXXXXXXXXXX"
```

- connect with ssh:
```
ssh -i ssh_user.key -p 12222 localhost list-hostmap
```
