### ISSUE TITLE
Client can reach lighthouse, but handshake times out.

### ISSUE THREAD

**Issue by spacehitchhiker42** [slackhq/nebula#697]
I've set up a lighthouse and a client node. The client is my home machine, and the lighthouse is a digitalocean droplet. When running Nebula, the lighthouse is printing out messages that it's receiving handshakes from the node, but the node says that the handshake timed out after every 10 handshakes that it sends.

Anyone else run across this problem before?

lighthouse config.yml
```
pki:
  ca: /opt/nebula/ca.crt
  cert: /opt/nebula/lighthouse.crt
  key: /opt/nebula/lighthouse.key


static_host_map:
  "192.168.42.1": ["146.190.2.148:4242"]

lighthouse:
  am_lighthouse: true


listen:
  host: 0.0.0.0
  port: 4242

firewall:
  outbound:
    - port: any
      proto: any
      host: any

  inbound:
    - port: any
      proto: any
      host: any

punchy:
  punch: true
  punch_back: true
  respond: true
  delay: 1s
```

node config.yaml 

```
pki:
  ca: /opt/nebula/ca.crt
  cert: /opt/nebula/jayne.crt
  key: /opt/nebula/jayne.key


static_host_map:
  "192.168.42.1": ["146.190.2.148:4242"]

lighthouse:
  am_lighthouse: false
  hosts:
    - "192.168.42.1"

listen:
  host: 0.0.0.0
  port: 4242

firewall:
  outbound:
    - port: any
      proto: any
      host: any

  inbound:
    - port: any
      proto: any
      host: any

punchy:
  punch: true
  punch_back: true
  respond: true
  delay: 1s
```
