### ISSUE TITLE
Misbehaving relay

### ISSUE THREAD

**Issue by chrisx8** [slackhq/nebula#705]
When I try to use relay to connect two machines behind NAT, the behavior is somewhat questionable...

- If relaying is disabled all systems, Nebula can establish direct connections between the two devices behind NAT.
- If relaying is enabled everywhere, Nebula always uses relay, even though it's not necessary (direct connection is possible, see above).
- If relaying is enabled on one of the two devices, the one with relay enabled becomes unreachable over Nebula.

Here's my setup:
- One system on AWS t2.micro (Linux x86_64): has public IP, serves as lighthouse and relay
- One laptop (MacOS arm64): no public IP
- One desktop (Linux x86_64): no public IP

Config on AWS:
```yaml
relay:
  am_relay: true
  use_relays: true
```

Config on laptop:
```yaml
relay:
  am_relay: true
  use_relays: true  # also tried false, see above
```

Config on desktop:
```yaml
relay:
  am_relay: true
  use_relays: true  # also tried false, see above
```
