### ISSUE TITLE
Slow/stuck transfer files in nebula network between America/Europe/Asia nodes.

### ISSUE THREAD

**Issue by asyslinux** [slackhq/nebula#723]
Hello, I can't figure out what's wrong and why the transfer rate drops significantly to KB / s, and almost freezes.
I tried to set lower mtu on two nodes(but not on all network nodes), but this is didn`t help. I tried to disable Europe lighthouse nodes in all network, but result same too. This problem i had on 1.5.2 version of Nebula too. Can anyone advise or check? Thank you.

Asia / Usa through Nebula:

`root@sg:/dev# rsync -av --progress america.vpn.ip:/tmp/50M.file /tmp/
root@america.vpn.ip's password:
receiving incremental file list
50M.file
      7,634,944  14%   67.03kB/s    0:11:08
      1,179,648   2%   71.06kB/s    0:12:01
      1,277,952   2%   58.15kB/s    0:14:39
      1,310,720   2%    9.79kB/s    1:27:00
      1,966,080   3%   45.57kB/s    0:18:27
      1,998,848   3%   39.42kB/s    0:21:19
      2,064,384   3%   46.14kB/s    0:18:11
      2,097,152   4%   49.54kB/s    0:16:56  `

Asia / Usa through Internet:

`root@sg:/dev# rsync -av --progress america.real.ip:/tmp/50M.file /tmp/
root@america.real.ip's password:
receiving incremental file list
50M.file
     31,817,728  60%    6.58MB/s    0:00:03`

With other transfers files from any continent to any continent in any direction - i have same problems.

I have 14 lighthouse nodes:
4 in Europe, 10 in America

Lighthouse configuration:

```
static_host_map:
  "10.10.0.1": ["1.2.3.1:12345"] #Europe
  "10.10.0.2": ["1.2.3.2:12345"] #Europe
  "10.10.0.3": ["1.2.3.3:12345"] #Europe
  "10.10.0.4": ["1.2.3.4:12345"] #Europe
  "10.10.0.5": ["1.2.3.5:12345"] #America
  "10.10.0.6": ["1.2.3.6:12345"] #America
  "10.10.0.7": ["1.2.3.7:12345"] #America
  "10.10.0.8": ["1.2.3.8:12345"] #America
  "10.10.0.9": ["1.2.3.9:12345"] #America
  "10.10.0.10": ["1.2.3.10:12345"] #America
  "10.10.0.11": ["1.2.3.11:12345"] #America
  "10.10.0.12": ["1.2.3.12:12345"] #America
  "10.10.0.13": ["1.2.3.13:12345"] #America
  "10.10.0.14": ["1.2.3.14:12345"] #America
lighthouse:
  am_lighthouse: true
  interval: 30
  hosts:
listen:
  host: 0.0.0.0
  port: 12345
punchy:
  punch: true
relay:
  am_relay: true
  use_relays: false
tun:
  disabled: false
  dev: n2n0
  drop_local_broadcast: true
  drop_multicast: true
  tx_queue: 500
  mtu: 1290
  routes:
  unsafe_routes: #Additionally i have some unsafe routes
    - route: 192.168.24.0/24
      via: 10.10.0.79
      mtu: 1290
      metric: 100
    - route: 192.168.32.0/24
      via: 10.10.0.87
      mtu: 1290
      metric: 100
logging:
  level: warning
  format: text
firewall:
  conntrack:
    tcp_timeout: 15m
    udp_timeout: 3m
    default_timeout: 10m
  outbound:
    - port: any
      proto: any
      host: any
  inbound:
    - port: any
      proto: any
      group: any
```

Others nodes configuration:

```
static_host_map:
  "10.10.0.1": ["1.2.3.1:12345"] #Europe
  "10.10.0.2": ["1.2.3.2:12345"] #Europe
  "10.10.0.3": ["1.2.3.3:12345"] #Europe
  "10.10.0.4": ["1.2.3.4:12345"] #Europe
  "10.10.0.5": ["1.2.3.5:12345"] #America
  "10.10.0.6": ["1.2.3.6:12345"] #America
  "10.10.0.7": ["1.2.3.7:12345"] #America
  "10.10.0.8": ["1.2.3.8:12345"] #America
  "10.10.0.9": ["1.2.3.9:12345"] #America
  "10.10.0.10": ["1.2.3.10:12345"] #America
  "10.10.0.11": ["1.2.3.11:12345"] #America
  "10.10.0.12": ["1.2.3.12:12345"] #America
  "10.10.0.13": ["1.2.3.13:12345"] #America
  "10.10.0.14": ["1.2.3.14:12345"] #America
lighthouse:
  am_lighthouse: false
  interval: 30
  hosts:
    - "10.10.0.1"
    - "10.10.0.2"
    - "10.10.0.3"
    - "10.10.0.4"
    - "10.10.0.5"
    - "10.10.0.6"
    - "10.10.0.7"
    - "10.10.0.8"
    - "10.10.0.9"
    - "10.10.0.10"
    - "10.10.0.11"
    - "10.10.0.12"
    - "10.10.0.13"
    - "10.10.0.14"
listen:
  host: 0.0.0.0
  port: 12345
punchy:
  punch: true
relay:
  relays:
    - "10.10.0.1"
    - "10.10.0.2"
    - "10.10.0.3"
    - "10.10.0.4"
    - "10.10.0.5"
    - "10.10.0.6"
    - "10.10.0.7"
    - "10.10.0.8"
    - "10.10.0.9"
    - "10.10.0.10"
    - "10.10.0.11"
    - "10.10.0.12"
    - "10.10.0.13"
    - "10.10.0.14"
  am_relay: false
  use_relays: true
tun:
  disabled: false
  dev: n2n0
  drop_local_broadcast: true
  drop_multicast: true
  tx_queue: 500
  mtu: 1290
  routes:
  unsafe_routes: #Additionally i have some unsafe routes
    - route: 192.168.24.0/24
      via: 10.10.0.79
      mtu: 1290
      metric: 100
    - route: 192.168.32.0/24
      via: 10.10.0.87
      mtu: 1290
      metric: 100
logging:
  level: warning
  format: text
firewall:
  conntrack:
    tcp_timeout: 15m
    udp_timeout: 3m
    default_timeout: 10m
  outbound:
    - port: any
      proto: any
      host: any
  inbound:
    - port: any
      proto: any
      group: any
```
