### ISSUE TITLE
🐛 BUG: Nebula through two Sonicwall firewalls NAT

### ISSUE THREAD

**Issue by alexio79** [slackhq/nebula#813]
### What version of `nebula` are you using?

1.6.1

### What operating system are you using?

Linux,Mac

### Describe the Bug

I have two branch offices where each side has a Sonicwall firewall and a private network behind NAT. I would like to be able to connect hosts at each site with Nebula as well as a variety of Linux and Mac laptops that can be connected to either network or other external networks.

I installed an external Lighthouse with a public IP that can correctly ping the hosts behind the two NATs. The hosts in the two locations successfully ping the Lighthouse server but not their respective servers in the other location.

For security reasons I don't want to use relays; I would like individual hosts to have specific ACLs.

Am I doing something wrong or is there simply no way to use Nebula with two networks behind NAT?

Thank you for your help.
Alessio

### Lighthouse config

``` 
pki:
  ca: /etc/nebula/ca.crt
  cert: /etc/nebula/host.crt
  key: /etc/nebula/host.key

static_host_map:
  "172.16.0.1": ["XXX.XXX.XXX.XXX:4242"]


lighthouse:
  am_lighthouse: true
  serve_dns: true
  dns:
    host: 172.16.0.1
    port: 53
  interval: 60

listen:
  host: 0.0.0.0
  port: 4242

punchy:
  punch: true
  respond: true

tun:
  disabled: false
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300
  routes:
  unsafe_routes:

logging:
  level: info
  format: text
  
firewall:
  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m

  outbound:
    - port: any
      proto: any
      host: any

  inbound:
    - port: any
      proto: icmp
      host: any

  inbound:
    - port: 53
      proto: udp
      group: any
``` 

### Servers config

``` 
pki:
  ca: /etc/nebula/ca.crt
  cert: /etc/nebula/host.crt
  key: /etc/nebula/host.key

static_host_map:
  "172.16.0.1": ["116.202.30.165:4242"]

lighthouse:
  am_lighthouse: false
  interval: 60
  hosts:
   - "172.16.0.1"

listen:
  host: 0.0.0.0
  port: 4242

punchy:
  punch: true
  respond: true

tun:
  disabled: false
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300
  routes:
  unsafe_routes:

logging:
  level: info
  format: text

firewall:
  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m

  outbound:
    - port: any
      proto: any
      host: any

  inbound:
    - port: any
      proto: icmp
      host: any

    - port: 443
      proto: tcp
      host: any
```
