### ISSUE TITLE
nodes and lighthouse can't communicate

### ISSUE THREAD

**Issue by String-syncfusion** [slackhq/nebula#836]
We have set up a lighthouse and a client node in digital ocean, after I start the nebula, I can see the handshake message being sent and receive.

But i can't be able to ping between them

**lighthouse config**
```
pki:

  ca: /opt/nebula/ca.crt
  cert: /opt/nebula/lighthouse.crt
  key: /opt/nebula/lighthouse. Key
static_host_map:
  "10.10.10.1": ["lighthousepublicip:4242"]
lighthouse:
  am_lighthouse: true
  interval: 60
listen:
  host: 0.0.0.0
  port: 4242
punchy:
  punch: true
  respond: true
tun:
  disabled: false
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300

logging:
  level: info
  format: text  

outbound:

    - port: any
      proto: any
      host: any

  inbound:
    - port: any
      proto: any
      host: any
```

**nodeconfig:-**
```
pki:

  ca: /opt/nebula/ca.crt
  cert: /opt/nebula/client2.crt
  key: /opt/nebula/client2. Key
static_host_map:
  "10.10.10.1": ["lighthousepublicip:4242"]
lighthouse:
  am_lighthouse: false
  interval: 60  
  
  hosts:
    - "10.10.10.1"

listen:
  host: 0.0.0.0
  port: 0
punchy:
  punch: true
  respond: true
tun:
  disabled: false
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300

logging:
  level: info
  format: text  

outbound:

    - port: any
      proto: any
      host: any

  inbound:
    - port: any
      proto: any
      host: any
```
Why am I facing this issue? Is there any other configuration which I need to do?

when I do tcpdump in lighthouse I can see

root@nebulalighthouse:/opt/nebula# tcpdump -n -i eth0 port 4242
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
13:14:14.236977 IP clientnodepublicip.58037 > lighthousepublicip.4242: UDP, length 236
13:14:14.532954 IP clientnodepublicip.58037 > lighthousepublicip.4242: UDP, length 236
13:14:14.932986 IP clientnodepublicip.58037 > lighthousepublicip.4242: UDP, length 236
