### ISSUE TITLE
🐛 BUG: 1.7+ no longer returns all routes available like 1.6

### ISSUE THREAD

**Issue by NihiliumOnMarz** [slackhq/nebula#880]
### Edit
I solved my issue.. It was my config I had to change the lighthouse interval from '0'
```
lighthouse:
  am_lighthouse: false
  serve_dns: false
  dns:
    host: ""
    port: 0
  interval: 0
  hosts:
  - 192.168.100.1
```
```
lighthouse:
  am_lighthouse: false
  serve_dns: false
  dns:
    host: ""
    port: 0
  interval: 1
  hosts:
  - 192.168.100.1
```

### What version of `nebula` are you using?

1.7.1

### What operating system are you using?

Windows, linux, android

### Describe the Bug

In Nebula 1.6 I was able to view all possible routes and connect on my local LAN and Nebula would figure it out with all possible IP addresses and 1.7 does not do that. 
Nebula 1.6
![Screenshot_20230521_220159_Nebula](https://github.com/slackhq/nebula/assets/120206371/7fb4e4b3-2d02-447d-961e-1d8a45e54c30)
Nebula 1.7
![Screenshot_20230521_220254_Nebula](https://github.com/slackhq/nebula/assets/120206371/b79ec0bd-8536-4501-90d2-0a829a5917dd)

### Logs from affected hosts

```
time="2023-05-21T22:02:06-04:00" level=info msg="Main HostMap created" network=192.168.100.2/24 preferredRanges="[]"
time="2023-05-21T22:02:06-04:00" level=info msg="punchy enabled"
time="2023-05-21T22:02:06-04:00" level=info msg="Loaded send_recv_error config" sendRecvError=always
time="2023-05-21T22:02:06-04:00" level=info msg="Nebula interface is active" boringcrypto=false build=1.7.1 interface=nebula1 network=192.168.100.2/24 udpAddr="[::]:53226"
time="2023-05-21T22:02:06-04:00" level=error msg="DNS resolution failed for static_map host" error="lookup test.marztk.com: i/o timeout" hostname=test.marztk.com network=ip4
time="2023-05-21T22:02:13-04:00" level=info msg="Handshake timed out" durationNs=7560563200 handshake="map[stage:1 style:ix_psk0]" initiatorIndex=4106051461 localIndex=4106051461 remoteIndex=0 udpAddrs="[]" vpnIp=192.168.100.255
time="2023-05-21T22:02:13-04:00" level=info msg="Handshake timed out" durationNs=7562186600 handshake="map[stage:1 style:ix_psk0]" initiatorIndex=4106299153 localIndex=4106299153 remoteIndex=0 udpAddrs="[]" vpnIp=192.168.100.1
time="2023-05-21T22:02:26-04:00" level=info msg="Handshake timed out" durationNs=7292937500 handshake="map[stage:1 style:ix_psk0]" initiatorIndex=2753782361 localIndex=2753782361 remoteIndex=0 udpAddrs="[]" vpnIp=192.168.100.1
time="2023-05-21T22:02:35-04:00" level=info msg="Handshake timed out" durationNs=6693977800 handshake="map[stage:1 style:ix_psk0]" initiatorIndex=817379357 localIndex=817379357 remoteIndex=0 udpAddrs="[]" vpnIp=192.168.100.1
time="2023-05-21T22:02:36-04:00" level=info msg="DNS results changed for host list" newSet="map[198.254.93.175:8080:{}]" origSet="&map[]"
time="2023-05-21T22:02:38-04:00" level=info msg="Handshake message sent" handshake="map[stage:1 style:ix_psk0]" initiatorIndex=3254122298 localIndex=3254122298 remoteIndex=0 udpAddrs="[198.254.93.175:8080]" vpnIp=192.168.100.1
time="2023-05-21T22:02:38-04:00" level=info msg="Handshake message received" certName=lighthouse1 durationNs=35008400 fingerprint=93b190b78a215b0778d77070e780d5a7ee7595d020891f2cbe5a44b4c7409b26 handshake="map[stage:2 style:ix_psk0]" initiatorIndex=3254122298 issuer=032eb8334b2f8640c0360d3b9cc0c6392adfd1436089b2efe132126ee2734b3a remoteIndex=3254122298 responderIndex=3828226950 sentCachedPackets=1 udpAddr="198.254.93.175:8080" vpnIp=192.168.100.1
time="2023-05-21T22:02:43-04:00" level=info msg="Handshake message sent" handshake="map[stage:1 style:ix_psk0]" initiatorIndex=2604234914 localIndex=2604234914 remoteIndex=0 udpAddrs="[192.111.70.127:41920]" vpnIp=192.168.100.5
time="2023-05-21T22:02:50-04:00" level=info msg="Handshake timed out" durationNs=6693126600 handshake="map[stage:1 style:ix_psk0]" initiatorIndex=2604234914 localIndex=2604234914 remoteIndex=0 udpAddrs="[192.111.70.127:41920]" vpnIp=192.168.100.5
time="2023-05-21T22:02:51-04:00" level=info msg="Handshake message sent" handshake="map[stage:1 style:ix_psk0]" initiatorIndex=2232227542 localIndex=2232227542 remoteIndex=0 udpAddrs="[192.111.70.127:41920]" vpnIp=192.168.100.5
time="2023-05-21T22:02:58-04:00" level=info msg="Handshake timed out" durationNs=6686672100 handshake="map[stage:1 style:ix_psk0]" initiatorIndex=2232227542 localIndex=2232227542 remoteIndex=0 udpAddrs="[192.111.70.127:41920]" vpnIp=192.168.100.5
time="2023-05-21T22:02:59-04:00" level=info msg="Handshake message sent" handshake="map[stage:1 style:ix_psk0]" initiatorIndex=1325813321 localIndex=1325813321 remoteIndex=0 udpAddrs="[192.111.70.127:41920]" vpnIp=192.168.100.5
time="2023-05-21T22:03:06-04:00" level=info msg="Handshake timed out" durationNs=6881596600 handshake="map[stage:1 style:ix_psk0]" initiatorIndex=1325813321 localIndex=1325813321 remoteIndex=0 udpAddrs="[192.111.70.127:41920]" vpnIp=192.168.100.5
time="2023-05-21T22:03:06-04:00" level=info msg="Handshake message sent" handshake="map[stage:1 style:ix_psk0]" initiatorIndex=3228385692 localIndex=3228385692 remoteIndex=0 udpAddrs="[192.111.70.127:41920]" vpnIp=192.168.100.5
time="2023-05-21T22:03:07-04:00" level=info msg="Handshake message received" certName=Nick23 fingerprint=404436f4d1e017970ca82f0218a5406398ed920ffc800c3646d3a816fa5720f1 handshake="map[stage:1 style:ix_psk0]" initiatorIndex=3624247415 issuer=032eb8334b2f8640c0360d3b9cc0c6392adfd1436089b2efe132126ee2734b3a remoteIndex=0 responderIndex=0 udpAddr="192.168.50.189:41920" vpnIp=192.168.100.5
time="2023-05-21T22:03:07-04:00" level=info msg="Handshake message sent" certName=Nick23 fingerprint=404436f4d1e017970ca82f0218a5406398ed920ffc800c3646d3a816fa5720f1 handshake="map[stage:2 style:ix_psk0]" initiatorIndex=3624247415 issuer=032eb8334b2f8640c0360d3b9cc0c6392adfd1436089b2efe132126ee2734b3a remoteIndex=0 responderIndex=1984952898 sentCachedPackets=0 udpAddr="192.168.50.189:41920" vpnIp=192.168.100.5
time="2023-05-21T22:03:07-04:00" level=info msg="Handshake message sent" handshake="map[stage:1 style:ix_psk0]" initiatorIndex=3228385692 localIndex=3228385692 remoteIndex=0 udpAddrs="[192.111.70.127:41920 192.168.50.189:41920]" vpnIp=192.168.100.5
time="2023-05-21T22:03:13-04:00" level=info msg="Handshake timed out" durationNs=6639012000 handshake="map[stage:1 style:ix_psk0]" initiatorIndex=3228385692 localIndex=3228385692 remoteIndex=0 udpAddrs="[192.111.70.127:41920 192.168.50.189:41920]" vpnIp=192.168.100.5
time="2023-05-21T22:05:16-04:00" level=info msg="Handshake timed out" durationNs=6804059100 handshake="map[stage:1 style:ix_psk0]" initiatorIndex=745126459 localIndex=745126459 remoteIndex=0 udpAddrs="[]" vpnIp=192.168.100.255
time="2023-05-21T22:05:24-04:00" level=info msg="Handshake timed out" durationNs=6804509400 handshake="map[stage:1 style:ix_psk0]" initiatorIndex=4176406907 localIndex=4176406907 remoteIndex=0 udpAddrs="[]" vpnIp=192.168.100.255
time="2023-05-21T22:09:27-04:00" level=info msg="Handshake timed out" durationNs=6993957000 handshake="map[stage:1 style:ix_psk0]" initiatorIndex=2302043396 localIndex=2302043396 remoteIndex=0 udpAddrs="[]" vpnIp=192.168.100.255
time="2023-05-21T22:09:34-04:00" level=info msg="Caught signal, shutting down" signal=interrupt
time="2023-05-21T22:09:35-04:00" level=info msg=Goodbye
```

### Config files from affected hosts

```
pki:
  ca: ./ca.crt
  cert: ./laptop1.crt
  key: ./laptop1.key
  blacklist: []
static_host_map:
  192.168.100.1:
  - test.marztk.com:8080
lighthouse:
  am_lighthouse: false
  serve_dns: false
  dns:
    host: ""
    port: 0
  interval: 0
  hosts:
  - 192.168.100.1
listen:
  host: 0.0.0.0
  port: 0
  batch: 64
  read_buffer: 0
  write_buffer: 0
punchy:
  punch: true
  respond: true
  delay: 5s
cipher: aes
local_range: ""
sshd:
  enabled: false
  listen: ""
  host_key: ""
  authorized_users: []
tun:
  dev: nebs1
  drop_local_broadcast: true
  drop_multicast: true
  tx_queue: 500
  mtu: 1300
  routes: []
  unsafe_routes: []
logging:
  level: info
  format: text
stats:
  type: ""
  interval: ""
  prefix: ""
  protocol: ""
  host: ""
  listen: ""
  path: ""
  namespace: ""
  subsystem: ""
handshakes:
  try_interval: 100ms
  retries: 20
  wait_rotation: 5
firewall:
  conntrack:
    tcp_timeout: 120h
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000
  outbound:
  - port: any
    proto: any
    host: any
  inbound: 
  - port: any
    proto: any
    host: any
relays:
  #am_relay: true
  use_relays: true
```

**Comment by NihiliumOnMarz** [comment]
I solved my issue.. It was my config I had to change the lighthouse interval from '0'
```
lighthouse:
  am_lighthouse: false
  serve_dns: false
  dns:
    host: ""
    port: 0
  interval: 0
  hosts:
  - 192.168.100.1
```
```
lighthouse:
  am_lighthouse: false
  serve_dns: false
  dns:
    host: ""
    port: 0
  interval: 1
  hosts:
  - 192.168.100.1
```
