### ISSUE TITLE
🐛 BUG:Nebula cannot obtain the correct dns server address from the system

### ISSUE THREAD

**Issue by aa51513** [slackhq/nebula#909]
### What version of `nebula` are you using?

1.7.2

### What operating system are you using?

Linux ( Arm64 )

### Describe the Bug

When starting nebula, an error is reported: 
`ERRO[0000] DNS resolution failed for static_map host error="lookup mynebula.server.com on [::1]:53: read udp [::1]:39679->[:: 1]:53: read: connection refused "hostname=mynebula.server.com network=ip4`

It looks like it can't get the correct dns server address from the system, but I type dig command and everything is normal：

```
~ $ dig www.google.com

; <<>> DiG 9.16.41 <<>> www.google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 2327
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.google.com.			IN	A

;; ANSWER SECTION:
www.google.com.		128	IN	A	104.244.46.52

;; Query time: 30 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed Jun 21 13:19:00 CST 2023
;; MSG SIZE  rcvd: 48
```

As a supplement, the following are the contents of the file `/etc/resolv.conf`  on my server:
```
nameserver 8.8.8.8
nameserver 8.8.4.4
```

I am very confused, why Nebula uses `[::1]:53` as the address of the dns server, regardless of the system configuration

Please evaluate whether the optional configuration item of dns server address should be added to the configuration file

### Logs from affected hosts

`ERRO[0000] DNS resolution failed for static_map host error="lookup mynebula.server.com on [::1]:53: read udp [::1]:39679->[:: 1]:53: read: connection refused "hostname=mynebula.server.com network=ip4`

### Config files from affected hosts

```
pki:
  ca: /etc/nebula/ca.crt
  cert: /etc/nebula/nebula.crt
  key: /etc/nebula/nebula.key
static_host_map:
  "10.10.10.1": ["mynebula.server.com:45445"]
lighthouse:
  am_lighthouse: false
  interval: 60
  hosts:
    - "10.10.10.1"
listen:
  host: "::"
  port: 45445
punchy:
  punch: true
relay:
  am_relay: true
  use_relays: true
tun:
  disabled: true
  dev: nebula
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300
  routes:
  unsafe_routes:
logging:
  level: warning
  format: text
firewall:
  outbound_action: drop
  inbound_action: drop
  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m
  outbound:
    - port: any
      proto: any
      host: any
  inbound:
    - port: any
      proto: icmp
      host: any
```
