### ISSUE TITLE
🐛 BUG: Firewall issues when using relays

### ISSUE THREAD

**Issue by kylerky** [slackhq/nebula#918]
### What version of `nebula` are you using?

1.7.2

### What operating system are you using?

Linux

### Describe the Bug

It seems that the firewall puts restrictions on the relays besides the sources.

I have three machines A, B and C. A and B are behind NATs and they need a relay, C, to talk to each other. C is also the lighthouse for A and B. B has a firewall configuration that only permits connection from a certain group G. A and B are in G.

The problem is that if C is not in the group G then A and B cannot talk to each other via C. If C is in the group, everything works.

I think the firewall should not care about which relay a connection is from but instead should do a end-to-end verification. In this way, nodes are free to choose which relays to use.

**Comment by JohnMaguire** [comment]
@kylerky Hi there, can you please share the firewall config for all three hosts? thanks!

**Comment by kylerky** [comment]
Hi @JohnMaguire . I am giving below the working configurations and certificates of A, B and C in order. The only difference when it does not work is that there is no group in C's certificate.

## A's Config
```
NebulaCertificate {
        Details {
                Name: A
                Ips: [
                        172.16.100.14/12
                ]
                Subnets: []
                Groups: [
                        "lab"
                        "home"
                ]
                Not before: 2023-07-19 09:46:07 +0800 CST
                Not After: 2024-07-16 15:06:52 +0800 CST
                Is CA: false
                Issuer: ...
                Public key: ...
        }
        Fingerprint: ...
        Signature: ...
}
```
```
relay:
  relays:
    - 172.16.100.10
  am_relay: false
  use_relays: true

firewall:
  outbound_action: drop
  inbound_action: drop

  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m

  outbound:
    # Allow all outbound traffic from this node
    - port: any
      proto: any
      host: any

  inbound:
    # Allow icmp between any nebula hosts
    - port: any
      proto: icmp
      host: any
```
## B's Config
```
NebulaCertificate {
        Details {
                Name: B
                Ips: [
                        172.16.101.11/12
                ]
                Subnets: []
                Groups: [
                        "lab"
                ]
                Not before: 2023-07-19 10:15:52 +0800 CST
                Not After: 2024-07-16 15:06:52 +0800 CST
                Is CA: false
                Issuer: ...
                Public key: ...
                Curve: CURVE25519
        }
        Fingerprint: ..
        Signature: ...
}
```
```
relay:
  relays:
    - 172.16.100.10
  am_relay: false
  use_relays: true

firewall:
  outbound_action: drop
  inbound_action: drop

  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m

  outbound:
    # Allow all outbound traffic from this node
    - port: any
      proto: any
      host: any

  inbound:
    # Allow icmp between any nebula hosts
    - port: any
      proto: icmp
      host: any

    # Allow tcp/443 from any host with BOTH laptop and home group
    - port: any
      proto: any
      groups:
        - lab
```
## C's Config
```
NebulaCertificate {
        Details {
                Name: C
                Ips: [
                        172.16.100.10/12
                ]
                Subnets: []
                Groups: [
                        "lab"
                ]
                Not before: 2023-07-19 10:26:09 +0800 CST
                Not After: 2024-07-16 15:06:52 +0800 CST
                Is CA: false
                Issuer: ...
                Public key: ...
                Curve: CURVE25519
        }
        Fingerprint: ...
        Signature: ...
}
```
```
relay:
  am_relay: true
  use_relays: true

firewall:
  outbound_action: drop
  inbound_action: drop

  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m

  outbound:
    # Allow all outbound traffic from this node
    - port: any
      proto: any
      host: any

  inbound:
    # Allow icmp between any nebula hosts
    - port: any
      proto: icmp
      host: any
```
