### ISSUE TITLE
Firewall "group" option doesn't work

### ISSUE THREAD

**Issue by einsteinx2** [slackhq/nebula#96]
The certificate on my laptop has 3 groups: `laptop`, `home`, and `ssh`:
```
Groups: [
			"laptop"
			"home"
			"ssh"
		]
```

The firewall rule on my server is as follows:

```
# Allow tcp/22 (ssh) from any host with ssh group
    - port: 22
      proto: tcp
      group:
        - ssh
```

And I can see that the rule is being set correctly:
```
Dec 13 20:33:59 arq nebula[24609]: time="2019-12-13T20:33:59Z" level=info msg="Firewall rule added" firewallRule="map[caName: caSha: direction:incoming endPort:22 groups:[[ssh]] host: ip:<nil> proto:6 startPort:22]"
```

However, if I try to ssh to that server, the firewall blocks the connection. So I changed the firewall rule to use the `groups` option with all three groups that are in my laptop cert:
```
    # Allow tcp/22 (ssh) from any host with ssh group
    - port: 22
      proto: tcp
      groups:
        - laptop
        - home
        - ssh
```

And I can see that the rule is being set correctly:
```
Dec 13 20:32:24 plex nebula[23885]: time="2019-12-13T20:32:24Z" level=info msg="Firewall rule added" firewallRule="map[caName: caSha: direction:incoming endPort:22 groups:[laptop home ssh] host: ip:<nil> proto:6 startPort:22]"
```

After that change, I can successfully ssh to the server.

Given that the `groups` option is an `AND` rather than an `OR`, I assumed that the purpose of the `group` option is to allow access to any machine with that group in its cert, even if it has other groups. As an additional test, I went ahead and changed the cert on my laptop to only have the `ssh` group and switched the server back to using the `group` option with only the `ssh` group and it still blocks the connection...

So it would seem that the `group` option is completely non-functional. Am I missing something obvious, or is this a bug? 

How is the `group` firewall option supposed to work? 

I'd like to be able to have multiple groups in my laptop's cert and then specify all of my servers to allow any machine with the `ssh` group to connect. In the meantime, I'll setup my server configurations to use the `groups` option, but that would only allow my laptop to connect. If I wanted to, for example, allow another server to connect, I'd like to be able to just add it to the `ssh` group without also putting it in the `laptop` and `home` groups.
