### ISSUE TITLE
🐛 BUG: nebula interface can come up before lighthouse hostnames are resolved

### ISSUE THREAD

**Issue by bloominstrong** [slackhq/nebula#966]
### What version of `nebula` are you using?

1.7.2

### What operating system are you using?

Arch Linux

### Describe the Bug

When using systemd.network and routing all DNS over nebula the interface can come up before the hostname of the light house is resolved, which results in the system trying to resolve the lighthouses host name over the nebula network which it cannot connect to because it cannot resolve the lighthouse's hostname. This obvioulsy leaves DNS down for the whole system.

I say can because most of the time the interface comes up before the hostname is resolved but not every time and go is doing some level of caching so normally I reboot the whole system to test.

The issue appears to be the the DNS resolution happens in the background and so there can be a race condition, this change came in from #796 so back to 1.7.0 is affected.

Using the Pure Go or native resolver does not make a difference.
```
export GODEBUG=netdns=go    # force pure Go resolver
export GODEBUG=netdns=cgo   # force native resolver (cgo, win32)
```

The solution to this issue should be to resolver the static_host_map before the interface is created, this can be done with a simple test of adding an early net.LookupHost() in main.go as I have done below.
```
--- a/main.go
+++ b/main.go
@@ -44,6 +44,7 @@ func Main(c *config.C, configTest bool, buildVersion string, logger *logrus.Logg
                l.Println(string(b))
        }
 
+       net.LookupHost("mydomain.com")
        err := configLogger(l, c)
        if err != nil {
                return nil, util.NewContextualError("Failed to configure the logger", nil, err)
```
I have been running that on my own 1.7.2 build for ~ 2 weeks now and have not had the issue appear again

### Logs from affected hosts

```
level=error msg="DNS resolution failed for static_map host" error="lookup mydomain.com: i/o timeout" hostname=mydomain.com network=ip
```

### Config files from affected hosts

My PC Nebula config
```
static_host_map:
  "10.51.0.254": ["x.x.x.x:49153"]
  "10.51.0.5": ["mydomain.com:4242"]

lighthouse:
  am_lighthouse: false
  interval: 60
  hosts:
    - "10.51.0.254"
    - "10.51.0.5"

relay:
  relays:
    - "10.51.0.254"
    - "10.51.0.5"
  am_relay: false
  use_relays: true

tun:
  disabled: false
  dev: neb0
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300
```

My systemd.network config
systemd 254.1-1-arch
```
Name=neb*

[Network]
DNS=10.51.0.5
Domains=~.
KeepConfiguration=yes   #Needed to allow nebula ip settings to remain
```
